### ISSUE TITLE
Add count to list of active games

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1119]
Could your list of active games also show how many total games you're in? I think the old site did this.

**Comment by AdmiralJota** [comment]
I'd like to bump this issue, since A) I've been wanting it myself recently and B) it should be relatively simple to do, especially if we went with the "Active games (17)" option. 

We'd probably want it to change appropriately when you click on the Show/Hide Stale Games link, and for consistency, it'd make sense for the count to appear on both the active and closed games lists.

**Comment by AdmiralJota** [comment]
Gist: https://gist.github.com/AdmiralJota/8afe049bd2fd46dc23c4

Includes three changed methods in Overview.js (Overview.addTableStructure(), Overview.showPage() and Overview.toggleStaleGame()) and one new one (Overview.updateSectionHeaderCounts()).

**Comment by blackshadowshade** [comment]
So, I'm working on this, and I thought I'd put up screenshots so that we can start discussing whether we want this feature in this form or not. Personally, I think it might actually be better to have the number of active games as an extra line at the bottom of the table.

Without stale games:
![without stale games](https://cloud.githubusercontent.com/assets/2898401/11718469/364fef7c-9faa-11e5-9505-f658b77fc0a6.png)


With stale games:
![with stale games](https://cloud.githubusercontent.com/assets/2898401/11718475/3b0e71c8-9faa-11e5-8b83-20bc18bd1f87.png)

**Comment by AdmiralJota** [comment]
I have nothing against moving it to the bottom, but I think it also looks perfectly fine the way it is, IMO.

Are we at all concerned about vertical space? Probably not, since it'd be below anything important anyway.

**Comment by blackshadowshade** [comment]
I think the problem will be when we have a number of bracketed numbers meaning different things:
- one in the header with the number of games waiting on you
- one (possibly) after Next Game with the number of games waiting on you
- one in each table header with the total number of (visible) games in each table

In my opinion, we can only realistically expect users to assign one meaning to a bracketed number---any more, and we are risking confusion. If we want to have multiple counts visible on the same page, we need to specify them further, not just have a count. Something like "Total number of active games that are not stale: XXX" would work for me.

**Comment by irilyth** [comment]
I think in each of those cases, the number clearly refers to the thing preceding it. "New forum post (8)" means there are 8 new forum posts, "New players have joined the site (3)" means three new players have joined the site, etc.

I like the screenshots, and I don't have a strong feeling about stale games. Perhaps count them if stale games are shown, and not if they're hidden? Or is that too complicated?

**Comment by blackshadowshade** [comment]
If you look closely at the screenshots, you'll see that that logic is already implemented: the count refers to the number of visible games in each table.

**Comment by irilyth** [comment]
Oh whoops, I missed that stale games were shown in the second screenshot, because I am dumb. :^)

I think those screenshots look good, and I think we don't need an additional line with the number of active games, but don't feel strongly about it.

**Comment by dwvanstone** [comment]
This looks great.
