### ISSUE TITLE
looking up skill attacks can be unreasonably slow

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1404]
During radioactive testing, i came across the following pathological case --- this game takes 5 seconds to load (on either firefox or safari, without firebug enabled):
![slow_skill_lookup](https://cloud.githubusercontent.com/assets/2898207/5028546/b0b5e06c-6b0a-11e4-9bbc-8246d6520aa3.png)

It turns out that the full five seconds happens in one function, `BMAttackSkill::find_attack()`.  That's big enough that it might be worth an efficiency refactor of that function.

**Comment by jl8e** [comment]
Well, it’s entirely possible I was optimizing prematurely (or optimizing for an incorrect use case), and the naive search is actually going to be faster than building the lookup table. (And I have too much non-BM stuff occupying me to figure it out ATM.)

However, an obvious problem is that find_attack() bulds the hit table, then calls validate_attack() at least once, which builds the exact same hit table every time it’s called. (I may have done this; I don’t recall.)

**Comment by jl8e** [comment]
Having done some more thinking about it, I don’t think it’s as simple as “stingers make it slow” or even “big stingers make it slow”. AFAIK, Golo (the degenerate case I was worrying about) isn’t particularly slow.

My best guesses ATM are either it scales very badly with number of dice, or there’s some interaction I can’t visualize.

**Comment by cgolubi1** [comment]
On Thu, 12 Feb, 2015 at 12:10:47 -0800, Julian wrote:

> Having done some more thinking about it, I don’t think it’s as simple as “stingers make it slow” or even “big stingers make it slow”. AFAIK, Golo (the degenerate case I was worrying about) isn’t particularly slow.
> 
> My best guesses ATM are either it scales very badly with number of dice, or there’s some interaction I can’t visualize.

Julian: please try a test case using Aysez with U=30, and then let us
know what you think.  That's the degenerate case we have observed ---
all of the instances of this bug we have seen in which the page actually
does not return because PHP times out after 30 seconds have involved
Aysez with a large U swing.

**Comment by blackshadowshade** [comment]
Max vs Max is also slow, although not as slow as Aysez, so I agree with Julian that stinger is not the only problem.

**Comment by jl8e** [comment]
>Julian: please try a test case using Aysez with U=30, and then let us
know what you think.  That's the degenerate case we have observed ---
all of the instances of this bug we have seen in which the page actually
does not return because PHP times out after 30 seconds have involved
Aysez with a large U swing.

I certainly believe it; but the numbers involved don’t seem to be big enough to create the delays seen (even if building the table is O(n!), which it probably is), and I can’t really sit down with a profiler and debugger to figure it out ATM.

Having looked at it some more (without actually profiling or even running the code), the call to generate_hit_table in BMAttackSkill::validate_attack() is the culprit. The hit table for Aysez is pretty large, and as we search through it, we call validate_attack for every entry we search, for every one of the opponent’s dice, and we’re rebuilding the hit table every time we do so.

I’m also looking somewhat askance at the main loop in find_attack(), but I think Fire means it has to be done that way, although it can probably be better optimized.

**Comment by jl8e** [comment]
Also, if the initial code to test the target die values first were still there, that loop wouldn’t even run most of the time.

**Comment by blackshadowshade** [comment]
So, I'm looking at https://github.com/buttonmen-dev/buttonmen/blob/8cc38a78c158e85ac2be25de39d08811e9643371/src/engine/BMAttack.php, line 343, which is right back at the beginning when all the attack types were still in BMAttack.php.

In your comment

> Also, if the initial code to test the target die values first were still there, that loop wouldn’t even run most of the time.

what are you referring to?

I note that somewhere along the way, the lines

    if (!$this->hit_table) {
      $this->hit_table = new BMHitTable($this->validDice);
    }

have done missing, and perhaps that may make a difference.

**Comment by blackshadowshade** [comment]
The question, though, is whether the hit table ever expires in its validity as attackers and defenders change.

**Comment by jl8e** [comment]
>>Also, if the initial code to test the target die values first were still there, that loop wouldn’t even run most of the time.
>what are you referring to?

Lines 354-374 in that version. You cut them out in https://github.com/buttonmen-dev/buttonmen/commit/66f5435ecc893a75ec71d2c5136ec11b6e784362
There was a bug — it wasn’t calling validate_attack before returning true.

As for the test for the existence of the hit table, you removed that in https://github.com/buttonmen-dev/buttonmen/commit/0e2dc11cde988e510bb2e9cd903cf61e0bbb0b14
Given the other changes there,  I assume it was due to tests failing because the hit table wasn’t being rebuilt when you swapped dice around, but I don’t know if that’s actually a behaviour that happens in the actual usage pattern, or if it’s an artifact of the testing.

The creation of the hit table in every single validate_attack() call comes from https://github.com/buttonmen-dev/buttonmen/commit/5fbc8174c62d9b075048f1a0559c39f9bd10f21f
The reasons for that change are unclear to me.

**Comment by jl8e** [comment]
>The question, though, is whether the hit table ever expires in its validity as attackers and defenders change (taking into account fire, for example).

It’s built for a specific set of attacking dice, and doesn’t become invalid as long as those are the available attackers.

It doesn’t account for fire at all; that’s the purpose of the loop that’s being run.

**Comment by blackshadowshade** [comment]
Based on the conversation in #1532, I'm reopening this so that I can fix it better.

**Comment by blackshadowshade** [comment]
So, as a reminder to myself, what I need to do here is:
- remove the singleton nature of BMAttack->get_instance()
- add a check to validate_attack() to generate a hit table if it doesn't already exist
- fix unit tests
