### ISSUE TITLE
Report of attack results preempted by Fire dice turndown message

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1489]
This occurred on http://buttonweavers.com, not the dev site, though I don't know whether it would have happened differently there: In game http://buttonweavers.com/ui/game.html?game=2989 I made an attack that involved turning down a Fire die. Normally after an attack is made, text at the top (in green) shows what the results of the attack was. But after this turn (see image), all I got was "Successfully turned down fire [sic] dice" - which is not particularly interesting or helpful. 
The attack results *are* displayed as normal in the "Recent game activity" section at the bottom, so it's more of a peculiarity than a bug... but I still like always being able to see the results up there at the top.

![screen shot 2015-01-03 at 9 31 27 pm](https://cloud.githubusercontent.com/assets/6092544/5604654/458850b0-9399-11e4-8730-e0f2f2c85ad8.jpg)

**Comment by cgolubi1** [comment]
At the moment, this should be the same behavior on both prod and dev.  AFAIK, there's no reason this behavior couldn't be changed.

**Comment by irilyth** [comment]
I still like the idea of revamping how this UI works entirely -- see #1143.

**Comment by cgolubi1** [comment]
My feeling is that, for this month, as long as the UI works the same way for Skill attacks with Fire as for Power attacks with Fire, this issue is not a big deal.  I agree that it would be nice to fix it (and it's probably pretty trivial to fix it --- it's probably just a question of propagating the action log message back to the BMInterface message rather than overriding it with "successfully turned down"), but i don't think it's germane to this month's topic in particular (because this month's changes don't change how it works).
