### ISSUE TITLE
figure out inheritance (or other form of ordering) for not-yet-implemented skills

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1491]
This came up with Sideboard vs. Select dice, and I'm sure applies to many other dice.  There are some skills that depend on, or at least will be more easily implemented with the existence of other skills.  

For me this might help choose a bugfix of the month when I'd like to see a new skill applied.  It's sometimes a little disheartening when I realize my BotM will progress minutely because of unresolved issues with other skills.  The same when the BotM seems to cause more debate than action, even though both are progress.  Every once in a while it would be nice to choose something quick and easy so I can say, "Yay! My BotM is done!"

**Comment by ManvilleFog** [comment]
Something that is so closely related to this that it probably isn't a separate issue is categorizing skills.  I know this has been discussed as part of other issues, but I don't think it's been explicitly stated except in an old forum post.

**Comment by irilyth** [comment]
I don't know if this is part of this or not, but one thing we could do is update https://github.com/buttonmen-dev/buttonmen/wiki/Tester-guide:-supported-skills with the unimplemented skills; then we could include descriptions, known issues, dependencies, etc, all in one place.

**Comment by ManvilleFog** [comment]
Thanks.  And wow! it's been a long time since unimplemented skills has been updated.  Socrates, Flying Squirrel, and Japanese Beetle have been removed as dice skills and made into button level skills.  And there is a lot missing from the list.  

But I guess this is a good place to look for choosing a BotM.  It lists priorities, though I think that's based on how many DHS buttons it adds as opposed to dependencies.

**Comment by cgolubi1** [comment]
On Mon, 05 Jan, 2015 at 08:58:06 -0800, irilyth wrote:

> I don't know if this is part of this or not, but one thing we could do is update https://github.com/buttonmen-dev/buttonmen/wiki/Tester-guide:-supported-skills with the unimplemented skills; then we could include descriptions, known issues, dependencies, etc, all in one place.

There is a dedicated page containing a prioritized list of unimplemented skills: https://github.com/buttonmen-dev/buttonmen/wiki/Unimplemented-skills

**Comment by irilyth** [comment]
Would Time & Space require any frontend changes? If not, maybe it should be the next priority. I've been putting BFOTM points onto Warrior because I personally like it, but it doubtless needs frontend dev cycles. I could be persuaded to shift my BFOTM to T&S if that'd be useful for anything. (As it turns out, there are some T&S buttons who I personally would like to play. :^)

If T&S is also a long-term pipe-dream sort of thing, I'm happy to keep Warrior as my personal pet favorite skill. But if it wouldn't be all that hard -- especially e.g. for a Feb prod release timeframe. But maybe that's just crazy. :^)

Sort of more back to the subject of this ticket, I think it might be advantageous to identify things like this on the unimplemented skills page -- "frontend dev cycles" seems like a reasonable thing to identify as a dependency for skills that actually require that.

**Comment by blackshadowshade** [comment]
We should be able to implement Warrior (perhaps suboptimally) without any frontend changes.

**Comment by blackshadowshade** [comment]
Time and Space should also be fine without any frontend changes.

**Comment by blackshadowshade** [comment]
I *think* that I have labelled each of the skills with the tag 'UI' about whether it needs frontend work.

**Comment by irilyth** [comment]
Doesn't Warrior require a way to let you select a Warrior die to add to a Skill Attack? I guess you could just make them all selectable, and return an error if you select more than one. It might make sense to color or shade them in some way, but I bet that's not hard either. Just thinking aloud. :^)

**Comment by blackshadowshade** [comment]
Initially, I'll be supporting them much like I support Stealth dice: returning an error message if the selected dice do not form a valid attack.

**Comment by blackshadowshade** [comment]
I'm closing this because I'm considering issues of skill inheritance at the time when I implement new skills, so this isn't really a separate issue.
