### ISSUE TITLE
Clock wrong?

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1501]
An extremely minor matter, I realize, but on the alpha site all the timestamps are about six minutes earlier than they ought to be.
For instance, in game 3329 my most recent move shows up in the Recent Game Activity log as:

(2015-01-16 13:04:50)	jimmosk performed Power attack using [(12):10] against [Ho(4,8):4]; Defender Ho(4,8) was captured; Attacker (12) rerolled 10 => 11

When I actually made it around 13:11.

**Comment by cgolubi1** [comment]
I was totally confused about this issue, because i call www.buttonweavers.com "the prod site".  The dev site is the one that used to be alpha.buttonweavers.com (even though it isn't any more), so... anyway, yes, the clock is wrong on www.buttonweavers.com.  I should fix this.  It's not technical debt, it's an operational issue.  I just couldn't verify it because i was looking at the wrong site.

**Comment by cgolubi1** [comment]
So this is a difference between the vagrant base image i picked for AWS and the one i picked for virtualbox use --- the latter has ntp installed and configured reasonably, the former doesn't.  So i'll just setup some vagrant/puppet rules to configure ntp, and submit a pull request for that.
