### ISSUE TITLE
Internal error when calling submitChat (dev game #1536)

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1540]
I had entered this text in the chat box for dev game 1536 (http://dev.buttonweavers.com/ui/game.html?game=1536):

> Yeah, ok, so:
> 
> > irilyth performed Skill attack using [o(Z=4):1,g`(2):2] against [(5/10=5):2]; Defender (5/10=5) was captured; Attacker o(Z=4) rerolled 1 => 1; Attacker g`(2) recipe changed from g`(2) to g(2), rerolled 2 => 1
> 
> This shouldn't be legal, because the Warrior Stinger 2 doesn't have Stinger while it has Warrior. (Or, at least, that's how the old site did it.)

I tried to edit this to say this:

> Yeah, ok, so:
> 
> > irilyth performed Skill attack using [o(Z=4):1,g`(2):2] against [(5/10=5):2]; Defender (5/10=5) was captured; Attacker o(Z=4) rerolled 1 => 1; Attacker g`(2) recipe changed from g`(2) to g(2), rerolled 2 => 1
> 
> This shouldn't be legal, because the Warrior Stinger 2 doesn't have Stinger while it has Warrior. (Or, at least, that's how the old site did it.)
> 
> (And that's how we wrote it up here: "While they are out of play, they are completely out of play: They aren't part of your starting dice, they don't count for initiative, they can't be attacked, none of their other skills can be used, etc." Of course, I wrote that text, so. :^)
> 
> (That text also contradicts a clarification from the old site: The new text implies that Berserk Warrior *is* usable, because Berserk doesn't take effect until the die loses Warrior.)

When I click "Change game message", I get "Internal error when calling submitChat", and the chat entry doesn't change.

I tried adding one line "Test adding one line.", and got the same result.

I tried deleting the chat text and replacing it with "Test deleting everything.", and got the same result.

I speculate that this has something to do with having used a Warrior die in the attack.

**Comment by irilyth** [comment]
Huh, although in that same game, I'm not able to edit the chat message even after making an attack without a Warrior die.

In http://dev.buttonweavers.com/ui/game.html?game=1516, I was able to edit the chat message after I initially hadn't put one in at all, and then edit it again. That game has Warrior dice, but I didn't use one in this round.

**Comment by irilyth** [comment]
In http://dev.buttonweavers.com/ui/game.html?game=1509 (no Warrior dice), I entered a chat message when I made my attack, and was then able to edit it.

**Comment by blackshadowshade** [comment]
Either you were having connection problems to the server, or we should see something in the Apache error logs.

**Comment by irilyth** [comment]
Hmm, I was able to edit the chat in http://dev.buttonweavers.com/ui/game.html?game=1527 this morning after making an attack with a Warrior die, so maybe it's not entirely related to Warrior.

I wasn't having connection problems as far as I know -- everything else I tried to do with the site worked fine.

**Comment by cgolubi1** [comment]
You rang?
```
[Tue Feb 24 05:15:34 2015] [error] [client X.X.X.X] PHP Notice:  Undefined offset: 0 in /var/www/engine/BMInterface.php on line 3087, referer: http://dev.buttonweavers.com/ui/game.html?game=1536
[Tue Feb 24 05:16:00 2015] [error] [client X.X.X.X] PHP Notice:  Undefined offset: 0 in /var/www/engine/BMInterface.php on line 3087, referer: http://dev.buttonweavers.com/ui/game.html?game=1536
[Tue Feb 24 05:19:13 2015] [error] [client X.X.X.X] PHP Notice:  Undefined offset: 0 in /var/www/engine/BMInterface.php on line 3087, referer: http://dev.buttonweavers.com/ui/game.html?game=1536
[Tue Feb 24 05:19:34 2015] [error] [client X.X.X.X] PHP Notice:  Undefined offset: 0 in /var/www/engine/BMInterface.php on line 3087, referer: http://dev.buttonweavers.com/ui/game.html?game=1536
[Tue Feb 24 05:27:41 2015] [error] [client X.X.X.X] PHP Notice:  Undefined offset: 0 in /var/www/engine/BMInterface.php on line 3087, referer: http://dev.buttonweavers.com/ui/game.html?game=1536
```

**Comment by cgolubi1** [comment]
```
07:40:50 < irilyth> Data:
07:40:52 < irilyth> Not my tunr.
07:40:54 < irilyth> I do Add/Edit Chat.
07:40:56 < irilyth> No message yet.
07:41:00 < irilyth> I enter "Test test."
07:41:03 < irilyth> It works, and now that's in the log.
07:41:07 < irilyth> I do Add/Edit Chat again.
07:41:22 < irilyth> I replace the text with "Again?"
07:41:29 < irilyth> I get "You can't add a new chat message now".
07:41:37 < irilyth> (Which is different from internal error?)
07:42:11 < irilyth> Same test with 
                    http://dev.buttonweavers.com/ui/game.html?game=1510 works 
                    fine.
```

**Comment by cgolubi1** [comment]
The second thing irilyth found is actually #1517, not a new bug.  I'm trying to reproduce the internal error thing now.

**Comment by cgolubi1** [comment]
I'm having trouble reproducing this.  If it comes to it, i can replay y'all's game exactly as a responder test, but i'm not enthusiastic to do so.  irilyth, when you made the skill attack that went with the chat (the one which brought `g(2)` into play), did you chat *while* making that attack and then edit it afterwards, or only chat after making the attack?

**Comment by irilyth** [comment]
I think it was when I brought the die into play, but I tried again just now and couldn't reproduce it either.

Ah, no, it must have been after, because I'm quoting the results of bringing it into play. irilyth (2015-02-24 00:12:01) was the problematic chat entry, (2015-02-24 00:11:01) was the problematic log entry.

**Comment by cgolubi1** [comment]
> Ah, no, it must have been after, because I'm quoting the results of bringing it into play. irilyth (2015-02-24 00:12:01) was the problematic chat entry, (2015-02-24 00:11:01) was the problematic log entry.

When you edit chat, it updates the timestamp.  So either making that chat entry with the attack and then editing it, or making the chat entry for the first time after the attack, would lead to the evidence in the game.  That's why i asked, because i don't think there's a way to tell by looking at the game.

**Comment by irilyth** [comment]
Does editing the chat update the timestamp if there's an internal server and it fails?

**Comment by cgolubi1** [comment]
On Wed, 25 Feb, 2015 at 03:54:30 -0800, irilyth wrote:

> Does editing the chat update the timestamp if there's an internal server and it fails?

I would guess it depends somewhat on the internal error.  :>)  But in particular the two scenarios i was thinking of here were: (A) you chatted with the attack, then you edited the chat once successfully, and then edited the chat a second time (and failed), or (B) you didn't chat with the attack, then you added chat successfully, then edited the chat (and failed).

**Comment by irilyth** [comment]
Ja. In any case, I wasn't referring to the timestamp as proof of anything, but the contents: In the chat message, I include the text from the attack from the action log, which I couldn't have done if I was entering it at the same time as the attack, because that text wasn't in the action log yet when I made the attack.

**Comment by cgolubi1** [comment]
On Wed, 25 Feb, 2015 at 04:35:21 -0800, irilyth wrote:

> Ja. In any case, I wasn't referring to the timestamp as proof of anything, but the contents: In the chat message, I include the text from the attack from the action log, which I couldn't have done if I was entering it at the same time as the attack, because that text wasn't in the action log yet when I made the attack.

Yep!  Which of my cases (A) or (B) does that make impossible?  I assert they are both possible, and that which one happened might make a difference (however slight) in reproducing your weird bug.  That's why i was trying to ask.  But if you don't remember you don't remember, so let's not worry about it any more.

**Comment by cgolubi1** [comment]
So... i have a responder test for this, where i duplicated this game exactly and reproduced the bug.  It turns out that was totally unnecessary, because in the process of doing so, i found the bug, and it has nothing to do with any of our speculation.

In particular, this has nothing to do with Warrior dice, backticks, or anything like that.  The real bug symptom description is: if you have ornery dice, and in a given move you roll all of your ornery dice so that the "ornery reroll" phase is a noop, then you'll get an internal error if you try to edit chat due to a bug in BMInterface.

The mechanism of the bug is:
1. submit_chat() reads the most recent entry from the action log
2. there's a long-standing counting bug in the action log code, which i would have sworn there was an open issue for months ago, but i can't find it.  When you invoke `load_game_action_log($limit)`, it applies the limit at SQL select time, but if a particular entry wouldn't print anything, the log omits that entry.  So you can ask for 10 entries and only get 8, even though 10 printable entries exist.
3. in this case, the last action log entry is an ornery_reroll, but no ornery dice were rerolled because irilyth used them all in his attack.  so `load_game_action_log($game, 1)` returns no entries, and that causes `find_editable_chat_timestamp()` to barf on the lack of an action log entry, when if you look at the game you can see that plenty of action log entries exist.

You could imagine various patches around this, but my strong opinion is that the right fix is to unbreak `load_game_action_log()` --- if you ask for N entries and N entries exist, you should get N entries.  I'm not personally crazy about the noop `ornery_reroll` entries as an implementation strategy for ornery, but there are *some* legitimate use cases for suppression of action logs, so IMO it's more important to have action log loading work correctly in the presence of suppressed action logs, than to worry about ornery_reroll too much.

Anyway, the responder test i wrote is in https://github.com/cgolubi1/buttonmen/tree/1540_reproduce_bug --- if we decide we'd like a shorter reproduction game with fewer partially-implemented buttons, we can worry about that later.  For now, the test that's written is much better than the test that isn't written.
