### ISSUE TITLE
Chat comment partly duplicated if edited while opponent takes turn

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1549]
On the alpha site in game 4483, I made a chat comment, took my move, and then tried editing the comment to add a line.  While I was typing the other player moved, so when I pressed the Change Game Message button it gave me an error message... but then look what it did, in attached screencap. It *did*accept my added text, but put it and the original text as a new chat comment, after my next move. I don't believe the chatbox for that next turn was prepopulated with the initially-rejected text... though to be honest I'm not sure; I was so surprised to see the text appear that I quickly screencapped it and started writing this issue.

![screen shot 2015-02-26 at 3 57 38 pm](https://cloud.githubusercontent.com/assets/6092544/6401832/4215ce32-bdd1-11e4-8e4f-8eed1bb20684.jpg)

**Comment by blackshadowshade** [comment]
The front end doesn't know anything about the fact that it is duplicating the previous message. It simply loads the current message at the time you hit Add/Edit Chat.

The possible problem here is that the UI still submitted the text even though it submitted an error, presumable that it's not your turn, or that the game state is outdated.

**Comment by cgolubi1** [comment]
I can't trivially reproduce this --- if i do the sequence of actions:
* p1 attacks and chats
* p1 clicks Add/Edit chat and starts adding some more chat
* p2 attacks and chats
* p1 clicks Submit Chat

I get the state in this screencap:

![chat_edit_rejected](https://cloud.githubusercontent.com/assets/2898207/6426328/e6a1e150-bf22-11e4-861c-5d913b55a8a8.png)

Namely:
1. I get the error i would expect ("You can't edit the requested chat message now")
2. The chat message doesn't get submitted
3. What i was trying to chat remains in my edit box so i can submit it with the next attack if i want

IMO, that's the correct behavior, and it's what i see when i do this.  Why didn't jimmosk get this behavior?

**Comment by cgolubi1** [comment]
So, we know that some things related to chat are done as a function of timestamp, and that timestamps have 1-second granularity.  (IMO, we have to fix this.  It causes trouble for test code all the time, because test code may or may not get stuff done in under a second, but in principle it should also mean that humans will see weird behavior very occasionally.)

In this case, there's obviously no conflict between the time devious chatted/attacked (15:50:06) and the time jimmosk actually submitted his edited chat message (15:50:19).  But what if jimmosk submitted his initial attack/message at 15:49:44, then took 18 seconds to realise he had something else to say, and thus clicked edit at 15:50:06.  What effect would that have?  As far as i can tell, if there's a timestamp comparison bug to check for, it has to be that one.

**Comment by cgolubi1** [comment]
No, that doesn't make sense --- clicking Add/Edit Chat isn't an API action, it's UI-only.  The gameChatEditable timestamp is sent by loadGameData, and it doesn't change when you reload the page unless the game state has changed.

Unfortunately, my next speculative theory requires two bugs: what if jimmosk reloaded the page before submitting his chat update, and thus was running loadGameData at the moment devious submitted his attack, 15:50:06?  loadGameData isn't atomic, so what it says about gameChatEditable might not match the rest of the game state.  But this requires two bugs, first for loadGameData to fail in that way, and second for submitChat to behave inconsistently when given inconsistent input.

**Comment by cgolubi1** [comment]
Hmm, never mind, jimmosk: now that i look at the logs of this game more closely, i don't understand what you're saying happened.

> While I was typing the other player moved, so when I pressed the Change Game Message button it gave me an error message... but then look what it did, in attached screencap. It did accept my added text, but put it and the original text as a new chat comment, after my next move

What do you mean "after my next move"?  What order of actions do you think you took?  In other words: i assume you're not saying the site auto-attacked on your behalf when you tried to update chat, or you'd be reporting this as a more serious bug.  But in your narrative description of what happened, i don't see a reference to your second attack, the one you made at 15:50:19 that ended the round.

So what happened?  You submitted chat and it gave you an error and the chat message was gone, and then you did your next attack and suddenly the chat message showed up in your log?  Or something else?

**Comment by cgolubi1** [comment]
In case it takes awhile for jimmosk to loop back to this and i've lost my mental state about the problem: if what happened is in fact "You submitted chat and it gave you an error and the chat message was gone, and then you did your next attack and suddenly the chat message showed up in your log?", as i suggested, then i think there's no bug we can easily fix --- when your chat attempt gets rejected, the chat you tried to do stays in your chat box, and if you don't notice it's there and take some other action, that chat gets submitted along with your new action.

That's my best guess reconstruction of this at the moment, and i think losing a long chat message someone had typed in the box is sufficiently worse than any other behavior we can do that we can't fix this --- we certainly can't refrain from putting the chat back in the box when an error occurs, and i think a player in the same situation might very easily *expect* "okay, my chat is still in the box, i'm not touching the chat and submitting my attack, and the chat will get submitted now".  Obviously it's not what jimmosk expected in this case, but i think it's the correct behavior.

**Comment by cgolubi1** [comment]
Shadowshade, if you're still here: for the record, `BMInterface::load_api_game_data()` loads the action log first and then the chat log, while `BMInterface:submit_chat()` loads the chat log first and then the action log.  Then each one calls `find_editable_chat_timestamp()`, which uses both the action log and the chat log to see whether chat can be edited.

Do i have a narrative about how this causes a bug?  No, not really.  But since loading stuff isn't atomic, let's have everyone who calls `find_editable_chat_timestamp()` load their stuff in the same order, so that if there are timing edge cases which cause a bug, we only have to solve the action-before-chat case *or* the chat-before-action case, and not both.

**Comment by jimmosk** [comment]
While I didn't think the text was displayed in the chatbox when I made my 15:50:19 move, it could be that I just didn't see it. And until I'm able to duplicate it, I'll assume that was the case.

**Comment by jimmosk** [comment]
glassonion and I just confirmed that the text had been in the chatbox.  Sorry, there was no bug.
