### ISSUE TITLE
Mood doesn't trigger on Berserk Mood Swing dice

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1570]
When a Berserk Mood Swing die (Finngall has one of these) makes a Berserk Attack, the die halves (due to Beserk), but then does not change size when it rerolls (due to Mood Swing). See http://dev.buttonweavers.com/ui/game.html?game=1559 for an example of this in action.

**Comment by irilyth** [comment]
My intuition is that Berserk should halve the die first, and then Mood Swing should change its size (effectively making the halving irrelevant), but I don't feel strongly either way, and the text of the skills at the moment both seem to me to say that they happen before rerolling, without making it obvious which one would happen first.

If anyone feels strongly about which order they should happen in, do chime in.

**Comment by jimmosk** [comment]
Berserk is indeed supposed to happen before mood, according to the skill_order_array in https://github.com/buttonmen-dev/buttonmen/blob/master/src/engine/BMSkill.php

**Comment by blackshadowshade** [comment]
To interpret the skill order array, you need to take into account whether the skills interact in specific die hooks. The list of die hooks is at

https://github.com/buttonmen-dev/buttonmen/blob/master/notes/engine/List_of_die_hooks_and_skills.txt

from which it becomes clear that there is no direct interaction of Mood and Berserk.

**Comment by blackshadowshade** [comment]
Okay, I know what's going on here.

In the code, the order is:
- berserk attack occurs, causing the attacker to halve its sides (via BMDie->split()) and causes the die value to be unset
- mood triggers in the pre_roll stage, but because the value is not set, doesn't do anything
- die is rolled, causing to now have a value

The problem is step 2, which is there to stop mood dice triggering their mood skill at the beginning of a round. I guess I'll need to add some sort of flag, allowing Mood to trigger even when the die has no value.

**Comment by cgolubi1** [comment]
Would it make more sense to do the logic the other way, and add an isStartOfRound type flag to the game which anyone can use for stuff that only needs to happen (or not happen) at the start of the round?

**Comment by blackshadowshade** [comment]
I actually tried that, a long while ago, and it caused all sorts of loose ends that seemed impossible to clean up.

I'll go with using the HasJustSplit flag that already exists, I think.
