### ISSUE TITLE
reach consensus on short-term plan for fire overshooting

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1704]
#1596, which has been loaded on the dev site but not on the prod, fully supports optional fire assistance for power attacks (allowing attacking dice to be fired up to their full value) at the cost of displaying a fire turndown screen whenever fire assistance to power attacks is possible.

Test this implementation, and reach a rough consensus around either the current implementation or some other implementation plan which lets us push code to the prod site in October.

**Comment by dwvanstone** [comment]
I strongly suggest that the user needs to specify that they want to use a Fire die when they're doing a power attack before they go to that interim screen. The fire turndown screen is a very intimidating screen, particularly for a newbie.

**Comment by cgolubi1** [comment]
Just to keep this part of the conversation over here, rather than on #1143 --- i think basically everyone agrees that refactoring the API flow of Fire attacks is the right long-term solution.  However, i don't think anyone can do that this month (dates beginning with "September"), so i want to make sure the conversation we have here is focused on the new "Fire assistance on power attacks" code, and in particular that we're answering the question of whether the right answer, going into October, is:
* Go forward with #1596 as merged
* Make some minor tweaks to #1596 and go forward with it (some of those have been suggested on other tickets)
* Roll back #1596 until #1143 can be implemented --- don't push it to prod as is (whether or not #1143 can be implemented this month)

We still have time to think about this, but i just wanted to restate it, since it's the question we need to answer this month.

**Comment by irilyth** [comment]
> * Roll back #1596 until #1143 can be implemented --- don't push it to prod as is (whether or not #1143 can be implemented this month)

This one has my vote.

**Comment by dwvanstone** [comment]
This one also has my vote. I think the cost of newbies being confused is too high.

> Roll back #1596 until #1143 can be implemented --- don't push it to prod as is (whether or not #1143 can be implemented this month)

**Comment by blackshadowshade** [comment]
I'd like you to consider whether there *are* any minor tweaks that would cause you to accept this solution. Minor means:
- no new pages
- no new UI logic with dropdowns or popups

For example, adding a checkbox might be possible. Also, adding a user preference might be possible.

**Comment by blackshadowshade** [comment]
Also, unless another dev comes in and feels like tackling the API flow of Fire attacks, it's not going to happen for quite possibly more than a year (and that's being optimistic).

If this functionality is rejected now, I will be proposing that we rewrite the definition of fire to exclude fire overshooting, since it's obviously not missed enough. I know that I already have Chaos's vote for this, and I would be willing to back it too.

**Comment by irilyth** [comment]
I think a user preference would be ok, as long as the default was not to bring up the turndown screen for overshooting.

**Comment by dwvanstone** [comment]
It'll take me a while before I can commit to being a buttonmen dev, but this looks like a fun and tricky case to handle. 

I think a user preference is a fine solution.

**Comment by blackshadowshade** [comment]
Okay, let me take a look at how to implement a user preference (default off) that allows fire overshooting.

**Comment by cgolubi1** [comment]
My only worry with this is that it complicates testing a bit, because we're going to have to run regression tests both with the preference off and with it on.  I mean, we already have that problem with autopass, and it's not the end of the world, it just bifurcates the decision tree again every time we add another preference with game logic implications.

That said, i definitely think this is doable, and it's probably the best option, just wanted to point out that where we're going to introduce the complexity is in the testing.

**Comment by cgolubi1** [comment]
Meant to add: and we'll have to decide what the default is.  In the autopass case, "autopass on" is definitely considered the default, and gets basically all of the testing attention.  If there are edge case no-autopass bugs, we're likely to find out about them from users, not from our own testing.

I imagine in this case, overshooting-off will be the default, but we'll probably need to do enough testing with both long-term (for some values of "enough") to satisfy ourselves.

**Comment by jimmosk** [comment]
I'm not sure if this counts as a bug, but after turning down Fire dice in an attack the normal green text at the top of the results screen no longer gives any details about the actual attack and rerolls; it simply says "Successfully turned down fire dice", which is a lot less useful. Can that sentence be added to the normal result-text instead of replacing it?

**Comment by cgolubi1** [comment]
Jimmosk: let's take discussion of that issue and its priority to #1489, since it really is a different issue than this (it applies equally to Skill-based Fire overshooting as to Power-based Fire overshooting).

**Comment by cgolubi1** [comment]
Mentioning this here because it affects my thinking, even though the bug hasn't been filed yet - the bug seen in http://dev.buttonweavers.com/ui/game.html?game=1844 was *not* introduced by this month's changes.  It exists on prod too (or rather, it would exist on prod if there were prod buttons with Fire and Konstant).  It's trivial to reproduce by hand using Hawaii --- i'll get a responderTest at some point.

**Comment by cgolubi1** [comment]
So... those couple of comments made, i want to back up a little bit on this.

Possibly i shouldn't admit this in this forum, but, when the Fire overshooting pull was initially made, i considered simply ignoring it to death forever (and, in fact, it took me a fair amount of time to get to it, as shadowshade can attest, but always with the guise of some other thing it was reasonable to be looking at first).  The reason is that i thought (and still think) the change is a bad idea --- (1) it makes the already-difficult game logic about Fire a lot more complicated, (2) in order to support a use case which is very rarely actually beneficial to the player, (3) the entire question could be ducked by changing the Fire text to say that Fire only applies to Skill attacks, (4) starting up as a DHS player, i always thought Fire *did* only apply to Skill attacks, and was very surprised to find that anyone interpreted the skill definition any other way.  Then there's (5) the proposed implementation makes the UI worse for most players, which is what we've been talking about how to fix in this ticket.  But the gold standard UI of our dreams doesn't solve the core problem of the previous sentence --- more complicated logic to support a use case i don't think is important and which isn't how i thought the game worked.

However, at the end of the day, i didn't think it was fair to ignore the pull to death --- i try to have some sensitivity to the fact that i'm the only code tester, and what i do has a *lot* of impact on the pace of progress on the site.  Shadowshade has been very patient about that, i'd like to think in part because i've demonstrated that at least sometimes i'm right that a seemingly-simple change does have far-reaching impact... But this is a little beside the point.  The point is, i'm in this gating position, so it's not fair for me to intentionally leave a change to rot just because i personally don't like it.

So, i didn't --- i tested the Fire change, a lot.  The first round definitely introduced some logic bugs (as well as a bunch of action log and game message bugs beyond the ones y'all are complaining about here), and basically at some point i had to say, "Well, i don't *think* there are any more regressions" and throw it over the fence.  And of course y'all have found some regressions i didn't, mostly in the form of unclear UI, and now we're looking at those.  And the first couple of commenters on this thread said, "I don't like this because of the UI", and the proposal is to fix that by making the functionality optional, a fix which increases the backend complexity even further.

But here's the thing, and this is why i'm posting all this backstory.  That complexity has a real cost measured in time, which is our most limited currency here in the world of Button Men.  If we decide to test #1712 and bring in the user preference for fire overshooting, we have two options:
A. Every single time we test a logic change, we test it with the fire-overshooting preference off and we test it again with the fire-overshooting preference on.
B. Players who turn on fire-overshooting will see game logic bugs, possibly even serious ones (i.e. internal errors), and we will not make any real effort to prevent that.

Even if we choose B, the amount of additional testing effort is not zero --- we'll need to instrument responderTest to be able to handle either value of fire-overshooting so we can do *any* regression tests of case B, and i'll need to instrument my test stuff too, because whenever a player reports a fire-overshooting bug, we'll need to reproduce and fix it.  (I mean, or we could introduce an option C, in which we make the fire-overshooting preference available but really provide no support for it at all.  But that's not the way i want to work!)

So, i kind of said this in a previous comment, but now i'm saying it with more words: i am only willing to support the "fire-overshooting UI preference" compromise *if* we choose B, and the assumption is that relatively speaking fire-overshooting-on is an unsupported preference, players may have a bad experience, *and in deciding where to spend our development and test efforts, we are going to prioritize the needs of fire-overshooting-off players over fire-overshooting-on players*.  I don't love that compromise --- i'd rather support a simpler Fire implementation better and move on to other things, and i'd definitely like to hear a defense of why fire-overshooting is important in the context of the time cost of having it at all.

But, the nature of compromise is not loving things, and if everyone on this thread so far (devious, irilyth, jimmosk, shadowshade, afaik) is happy with fire-overshooting as a user preference with fire-overshooting-on as a second-class citizen in terms of game stability and support, i'm willing to go along with that and make the tradeoffs right now to get to at least that point.  I just want to draw the line in the sand that, in terms of pre-pull-merge testing, i'm *not* willing to treat fire-overshooting-on as a first-class citizen.

Thanks for slogging through all the background to get to the TL;DR, if you did.  I wanted to provide some justification, because i really do see choosing not to test things as a limitation that might affect user experience later, but i also think site progress will grind even further to a halt if i have to add fire-overshooting-on testing to my arsenal, and that's not a tradeoff i'm willing to make.

**Comment by irilyth** [comment]
My two cents:

> I don't love that compromise --- i'd rather support a simpler Fire implementation better and move on to other things

I've probably said this before, but just to be clear about it: Me too. I think it's completely acceptable not to fix any Fire-related bugs until we improve the implementation/UI/whatever. Even if that takes a year; I'm optimistic that a new dev will be able to tackle this sooner than that, but if we only have one dev, then I'd rather spend their time on things other than this.

**Comment by blackshadowshade** [comment]
I'm perfectly good with Chaos's preferred position, namely that fire overshooting *should* work, but won't be fully tested into the future. I agree that many players may not miss it at all, and it's mostly going to be there for those advanced players who are looking for the extra 1% win percentage in tournaments.

I think, however, that it is worth having as an option for advanced players. After all, much of the subtlety of Button Men is in those small percentage choices, be it in swing choice, or choice of attacking die, or even in choice of button. An expert Fire player *should* be able to exploit subtle advantages to outperform a new Fire player, and I think that this feature of fire overshooting is nice: not overly powerful, but useful in a limited number of situations.

**Comment by cgolubi1** [comment]
On Wed, 16 Sep, 2015 at 06:52:13 -0700, James Ong wrote:

> I'm perfectly good with Chaos's preferred position, namely that fire overshooting *should* work, but won't be fully tested into the future.

Just to clarify, my preferred position is for Fire to only be usable with Skill attacks.  But i am willing to sign on to the position that fire overshooting should work, but won't be fully tested into the future.  :>)

Chaos

**Comment by dwvanstone** [comment]
I feel it's weird that a setting in preferences will affect the rules of the game for that one player and not the other. One player gets to overshoot that can be an extra 1% advantage because of a setting in preferences and the other player can't overshoot at all. (I suppose this will be an incentive to dive into becoming a dev to try to implement some Fire UI improvements.)

Do we agree that this preference goes away once there are Fire UI improvements?

I'm also fine with this overshooting feature being potentially buggy (and not as well tested) until the improvements are made which may be a year from now.

**Comment by blackshadowshade** [comment]
I don't know if I agree that the preference goes away, even after Fire UI improvements.

For example, in the current software iteration of Magic: the Gathering, players start out with certain newbie safeguards in place that actually limit your options quite significantly, e.g., you can't target one of your own creatures with a destructive spell or effect. To deactivate these safeguards, it is necessary to manually unset a preference in the Options menu.

I think that it is a good thing to provide a simpler experience for newbie players, even if they do end up not being able to access the theoretical 1% boost, because the reduction in confusion may actually allow them to concentrate on playing better most of the time.

**Comment by irilyth** [comment]
> But, the nature of compromise is not loving things, and if everyone on this thread so far (devious, irilyth, jimmosk, shadowshade, afaik) is happy with fire-overshooting as a user preference with fire-overshooting-on as a second-class citizen in terms of game stability and support, i'm willing to go along with that and make the tradeoffs right now to get to at least that point.

So to summarize the options:

- Option A: The short-term position is "you can't turn down Fire dice more than you need to in order to have a legal attack".
  - Unwind the recent change that allows overshooting.
  - Accept that this is contrary to the official rules, but is a pretty small corner case.
  - Expect that this will likely be fixed when we revamp the Fire UI (#1143) and/or fix other things about the current Fire implementation (is there a ticket that talks about other things that need fixing)?

- Option B: The short-term position is "you can use Fire dice with a Power Attack, including overshooting.
  - Include a preference to enable or disable this, disabled by default.
  - All testing will be with the preference disabled.
  - If users report bugs that occur only with the preference enabled, they will be ignored. (Maybe set aside for "some day", but no one will try to reproduce them, fix them, or test a fix.)

And the opinions:

- @cgolubi1 prefers Option A, because Option B either makes testing significantly harder, or has us claiming that there may be bugs in code that we can't and won't test or fix and if folks encounter them that's just tough beans, neither of which is appealing.

- @irilyth prefers Option A, for more or less the same reasons as @cgolubi1, and further predicts that we're not actually going to be able to get away with "we will simply ignore bugs in this untestable thing", and thinks that Option A is perfectly acceptable as a short-term fix and that the cost of spending time implementing Option B is nowhere worth the benefit.

- @blackshadowshade prefers Option B, because not allowing overshooting is a rules bug, and rules bugs are really important -- "the site MUST correctly implement the rules of the game" is a top priority.

- @dwvanstone ... I'm not sure. Is conflicted? Doesn't like having a preference that effectively gives different players different rules; but also thinks it's a reasonable short-term approach?

I invite:

- @blackshadowshade to correct me if I'm wrong about why he likes Option B, and/or to just state his reasons/arguments himself and ignore my possibly inept summary. :^)

- @dwvanstone to clarify what he thinks.

- @jimmosk to chime in, as he has not yet.

- Everyone to correct anything I've said here that sounds wrong. :^)

RSVP.

**Comment by blackshadowshade** [comment]
irilyth is correct when he states my reason for preferring Option B. I believe, optimistically, that his estimate of the time to implement Option B is incorrect, and that most of the effort has already been put in. I don't believe that there will be huge server errors or critical bugs arising from the current implementation.

**Comment by dwvanstone** [comment]
I'm slightly confused. Right now on production can one use a Fire die for a Power Attack? (Not for overshooting but to raise the Berserk die value for an exact match.)

**Comment by dwvanstone** [comment]
[I asked that question because the negative of option B is "you can not use Fire Dice for a Power Attack".]

What matters to me is usability for the users and not putting too much stress on the developers. Both options A & B work for me, but I can't tell how much stress or unfinished work is involved with either option. Would @blackshadowshade be super sad with option A because he spent a lot of effort already creating overshooting and would be mad if it weren't implemented? Would @cgolubi1 be super sad with option B ? I feel like I have to pick personal sides to keep someone from being sad which is awkward.

I would enjoy the game of ButtonMen with overshooting and without overshooting. It gives me a little bit of joy to find weird corner cases and neat unheard of power moves but I personally wouldn't prioritize it very high. I'd say pick the option that gives the working devs the most joy since we're all volunteers doing this for the joy. [Until I'm a full-fledged dev I don't think my opinion should count for much.]

If it helps, @blackshadowshade , I'm now excited about reworking the Fire die UI and would want to make that one of my first tasks when I dive into the dev role.

**Comment by blackshadowshade** [comment]
Currently, yes, it is possible to commit a fire-assisted power attack, even including overshooting, as long as the attacker's value is less than the target value.

Regarding the amount of unfinished work, I consider fire overshooting to be *complete* from my point of view. I see *no* future work apart from Chaos's testing and approval.

@dwvanstone, I'm glad to hear that you're enthused about reworking the Fire die UI, but I think that you should think twice before diving into this task, for two reasons:
- This task requires intimate knowledge of the back-end, interface, and front-end
- I think you underestimate the difficulty of getting UI changes accepted by Chaos, and these will be *huge* UI changes that you will be proposing

I would also argue that there are easily 50 other UI issues that are more important than a reworking of the Fire UI, and if you were really interested in pouring a whole pile of time into BM, it would be far more useful to work on a new UI for Turbo Swing.

**Comment by dwvanstone** [comment]
Fair points about where to prioritizing my time when I do have time. It sounds like a revised Fire die UI is a good goal to have for years down the line once I understand the structures better.

**Comment by blackshadowshade** [comment]
Chaos and I have always seen the revised Fire UI as being an offshoot of the work on the new Turbo Swing UI, since much of the conceptual work will be tackled there.

**Comment by irilyth** [comment]
> Chaos and I have always seen the revised Fire UI as being an offshoot of the work on the new Turbo Swing UI, since much of the conceptual work will be tackled there.

Indeed, I've been predicting that they should be done at the same time because I think we want them to have a whole lot of look-and-feel in common.

**Comment by blackshadowshade** [comment]
From what we've seen in the past, it's easier for Chaos to approve many small pull requests than one big one. If someone were to submit a huge pull request for both Fire and Turbo Swing, I would anticipate that Chaos would ask for it to be split up into smaller pull requests.

**Comment by cgolubi1** [comment]
> From what we've seen in the past, it's easier for Chaos to approve many small pull requests than one big one. If someone were to submit a huge pull request for both Fire and Turbo Swing, I would anticipate that Chaos would ask for it to be split up into smaller pull requests.

Sounds right to me --- we're getting a bit off-topic here, but, as a prospective pull request submitter, i think the thing to think about in terms of making testing easy is what a tester is going to be looking for.  If you hand me a really big refactor, but it's purely a refactor and isn't supposed to change the behavior at all, it takes some time to verify that it doesn't change the behavior and make sure it looks reasonable, but it's not too bad.  And if you hand me a small change that does change the behavior, it's, again, maybe not trivial but tractable to make sure it does make the desired change and not others.

Where things tend to bog down is when changes *both* touch a lot of code *and* change the site behavior.  So, y'know, avoid that if you can, and if you can't, give me a lot of guidance in the pull request and code comments about what you're doing and why.

Okay, now back to your regularly scheduled debate.  :>)

**Comment by cgolubi1** [comment]
FWIW, this isn't my interpretation of option B:

>  - If users report bugs that occur only with the preference enabled, they will be ignored. (Maybe set aside for "some day", but no one will try to reproduce them, fix them, or test a fix.)

I don't think we can (or would want to) get away with ignoring a concrete bug report, especially a logic bug (i definitely think we'll be setting aside "this UI is unfriendly" type bugs) --- it's mostly that i'm not going to *look for* logic bugs when i do testing, nor ask the dev testers to do so.

Anyway, this is your reminder that we never actually did reach a consensus, and time is passing.  Unfortunately for me, that means i feel obligated to go ahead and test #1712 without knowing whether we are actually going to use it (and, let's be honest, at the point at which we've tested it and think it works, we're probably going to go ahead and use it).

I'm going to go ahead and work on testing #1712 and not try to get into my opinions about that, but as a reminder, especially to jimmosk the nonparticipatory, we're offering BFotM for driving this to consensus, and we made that offer because we figured it would be hard to do and thus needed a reward.  :>)

**Comment by dwvanstone** [comment]
Okay - this was a good clarification. If it's not too much bother for cgolubi1, my preference is option B. We'll have to rethink some of the Fire dice issues later.

**Comment by cgolubi1** [comment]
> We'll have to rethink some of the Fire dice issues later.

Okay.  I would like, whatever we choose, to put down the Fire issues for a good long while after this.  I would say that so far dealing with testing to get us to this point has put us back over a month, probably as much as two months, on working on other issues.  Maybe the pace of development will get faster and we won't have these tradeoffs, but let's assume it won't, and that whatever we're agreeing to now we're agreeing to have for the next (say) 12 months *without* another major revisit.  Is this compromise good enough for that?  If so, fine.  I'm pretty comfortable with #1712 based on my testing so far, and i've done most of the heavy lifting needed.  But if we're thinking "this is okay for now but we're going to have to revisit it *soon*"... let's talk about that.  Because i think we need to stop focusing on Fire and turn to other issues after this short-term consensus is resolved.

**Comment by dwvanstone** [comment]
I agree that _later_ can mean over 12 months from now.

**Comment by cgolubi1** [comment]
> I agree that later can mean over 12 months from now.

WFM.
