### ISSUE TITLE
Make nicer UI pages for not-yet-accepted and rejected games

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1731]
In #1727, we solve the issue of rejecting games (#205), but the UI stubs shown to the player are not pretty. Ideally, we should show relevant information about the game.

**Comment by jimmosk** [comment]
Moving this request here from https://github.com/buttonmen-dev/buttonmen/issues/1734:

Could there be a "Go to your next pending game (at least N)" link in the body of the "This game has been rejected" screen, same as there is on other game screens when you've done all you can on that game? (There's a Next Game link in the header, but some of us have gotten so used to having it be in the body that we never look up there.)

**Comment by cgolubi1** [comment]
WRT jimmosk's request: as long as when we lay the pages out, we don't set `includeFooter = false`, i believe you'll get that link for free.

**Comment by blackshadowshade** [comment]
The page for an unstarted new game should show the links to accept/reject (#1736).

**Comment by blackshadowshade** [comment]
I'm going to link in #1312 here so that it doesn't get lost.

**Comment by cgolubi1** [comment]
For the record, i would call this a prod-blocker if it were easier, because when you create a new game, you are given a link which goes to the game page, and the current behavior of that link is ugly and unhelpful.  I predict we will get a number of user complaints about that.

I think we can live without this for the benefit of getting the November release done, but it's a must-have for December.

**Comment by irilyth** [comment]
I agree, I think this should be a prod-blocker. I think it suffers particularly, from a PR point of view, because players won't understand why we had to punt it: The overview page has these nice links that do just the right thing, why can't the game page also just have those links?

**Comment by dwvanstone** [comment]
I notice that the New Games table does not have a link to the game. (Neither does "Your open games" on the Open Games page.) Perhaps a quick fix would be to have Rejected Games not have a link to the game for now until there is a nicer page.

**Comment by dwvanstone** [comment]
When as I user I create a game, I see this message:  "Game 1912 created successfully. Go to game page". I think this is the link you're saying doesn't work well. Maybe the "Go to game page" should be removed for now as well until there is a nicer page. (Perhaps "Waiting for opponent to accept" would now be more appropriate?)

**Comment by AdmiralJota** [comment]
I agree. I'm not sure we should even be encouraging people to think of the game as actually existing as a thing before anyone has joined it. From our point of view as programmers, it exists as a record in the DB. But from a player's point of view, it's still just a potential game that hasn't actually started yet. 

I don't think we should ever be linking to the game page for a game that hasn't actually started, unless some day in the future we have some special functionality that we want to put there that's specific to un-started games.

When you create an open game, the link is "Go to open games page" -- and that page is where you'll see your new game listed, waiting for an opponent. So when you create a game against a specific person, why not link back to your Overview page, since that's where you'll see this new game listed?

**Comment by irilyth** [comment]
The advantage of having new games show up as game pages is that when you next-game your way through your games that need action from you, you get these, which are games (if only potential ones) that need action from you. I think that's a nice feature.

**Comment by dwvanstone** [comment]
> So when you create a game against a specific person, why not link back to your Overview page, since that's where you'll see this new game listed?

That sounds like a good solution for now.

> I don't think we should ever be linking to the game page for a game that hasn't actually started...

I think it might be helpful for people (especially newbies) to be able to see the page with the buttons laid out with all of the recipes before they choose to accept the game. Otherwise they have to do a lot of clicking on buttons to see what they are before deciding to accept or reject.

**Comment by AdmiralJota** [comment]
> The advantage of having new games show up as game pages is that when you next-game your way through your games that need action from you, you get these, which are games (if only potential ones) that need action from you. I think that's a nice feature.

That's true. Although without having game pages for potential games, when you Next Game through, you'll land on the Overview page, which is the place where the actual UI for dealing with them already is (unlike active games, which you obviously can't actually interact with from the Overview page itself). 

That said, maybe it might be nice to have the list of games that people have challenged you to [i]first[/i] on the page, maybe even with some kind of highlighting, to make it really clear and obvious that this is a thing that you really ought to deal with right now.

**Comment by irilyth** [comment]
Yeah, I dunno -- it might depend on how much time a player spends in game pages vs on the overview page. And I may be scarred by the period when my overview page took twenty seconds to load, so I *never* went to it at all -- when I saw that I had no next game, I just closed the tab.

**Comment by cgolubi1** [comment]
Let me throw something out there about this issue (at the extremely high risk that it will be misunderstood and i'll get into more trouble): i am choosing not to call this a prod-blocker because of the combination of two specific reasons:
1. I do not think we can implement and iterate the top-line description of this issue and still make a 6 Nov release date
2. I think it is more important to get a Nov release even if the reject-game interface is slightly *broken* (and i am intentionally using the word broken here) to demonstrate progress to players

I'm fine with these outcomes:
A. Other people agree with me, we release reject-game as is, we get lots of complaints because of this issue (#1731), and we implement this for December
B. Other people determine that this issue is a prod-blocker, and we delay the November release for a week so we can include and test it
C. Other people determine that this issue is a prod-blocker and we don't have the nerve for the current frenetic pace of discussion, so we skip the November release

I am not happy with the outcome in which we implement a lot of hackish one-off UI code (like ripping game links out of places they obviously belong) to work around the lack of this issue.  That's all going to be wasted work.  Let's not do it.

**Comment by AdmiralJota** [comment]
When you say, "places they obviously belong", are you referring to the link that's displayed to a player after they challenge someone else to a game? If so, could you clarify why it's obvious that that link belongs there in the long term?

**Comment by dwvanstone** [comment]
I think this is an important enough feature that I'm proud and excited to have it released as is and would like to help make it even better for the December release. (The discussion of whether the links belong or not can wait until after this release is out.)

**Comment by irilyth** [comment]
> I think this should be a prod-blocker. I think it suffers particularly, from a PR point of view, because players won't understand why we had to punt it: The overview page has these nice links that do just the right thing, why can't the game page also just have those links?

To clarify, by "this" there, I meant specifically "have accept/reject links on the game page for new games", and *not* "the entirety of this ticket" -- I think there's a lot of nice-to-have-for-Dec stuff here, and the one thing I think should be a must-have for Nov is accept/reject links on the game page.

I think that the incremental progress of just having a naked accept/reject link on the game page for a new game, in Nov, and then a much nicer page in Dec, is way better than going live with the current page in Nov, and the same much nicer page in Dec.

If spinning that specific thing off into another ticket would help, I'm happy to do that.

**Comment by dwvanstone** [comment]
I hadn't heard clearly what the issue is. It's not that there's a link on the Overview page that sends users to an ugly page or that after making a game there's the "Go to Game Page" link to an ugly page. (I think fixing those can wait until December.) 

It's that the normal use of playing the game (clicking on "Go to your next pending game" or clicking on "Next game" from the menu) will send you to a page that only says "This game hasn't started yet" with no opportunity to start it and that feels shockingly broken.

Is that correct that that's the use case that's the prod-blocker? (I'm purposefully not proposing a solution to the problem, just trying to state the problem more clearly.)

**Comment by irilyth** [comment]
> It's that the normal use of playing the game (clicking on "Go to your next pending game" or clicking on "Next game" from the menu) will send you to a page that only says "This game hasn't started yet" with no opportunity to start it and that feels shockingly broken.

That's how I'd describe the prod-blocker level problem, yep.

**Comment by dwvanstone** [comment]
> That's how I'd describe the prod-blocker level problem, yep.

Until I experienced it I didn't think it was a problem. It doesn't even have the link "Go to your next pending game..." so you can't continue navigating through your games. I'm swayed by irilyth that this could feel very broken to a user. I think it would even warrant a delay of a week of there is no quick solution.

**Comment by blackshadowshade** [comment]
How are you guys getting to the game page? The intent currently is that new games and pending games NOT show up in the monitor, so if people are landing on the game page, I see *this* as the bug at the moment.

**Comment by cgolubi1** [comment]
On Tue, 03 Nov, 2015 at 14:25:02 -0800, James Ong wrote:

> How are you guys getting to the game page? The intent currently is that new games and pending games NOT show up in the monitor, so if people are landing on the game page, I see *this* as the bug at the moment.

1. When you create a new game, the "you just created a game" page links to the game you just created.

2. When you use "Next Game" to page through your active games, it takes you to both games that are active and new games that are waiting for you to decide whether to accept them.

I strongly disagree that 1 is a bug.  And i don't really think 2 is either, though i'll defer if the consensus is that it is.

**Comment by cgolubi1** [comment]
Okay.  So there are now stub pages for games which haven't yet been accepted (hooray!), and you can accept, reject, or cancel from those pages.  Is that sufficient for this issue not to be a blocker of the November release?  If not, what else do we need?

IMO it is absolutely sufficient, and everything else on this issue can wait until the December release.  Check it out on dev and see what y'all think.

**Comment by AdmiralJota** [comment]
I would certainly think this would address any blocking issue here.

**Comment by irilyth** [comment]
I don't think anything else on this ticket is a prod-blocker for November.

**Comment by dwvanstone** [comment]
> How are you guys getting to the game page? 

Let me add to Josh's list that the "Go to your next pending game (at least #)" link goes to the uncreated game. (This is how I navigate through my open games -- I don't use the "Next Game" at the top.)

I agree there are no prod-blockers for me anymore.

**Comment by blackshadowshade** [comment]
Once #1817 is accepted, I think that this issue can be considered to be fully addressed.

**Comment by blackshadowshade** [comment]
So, once the accepted pull requests have been deployed to dev, I'd like the testers to comment on whether this issue has been addressed fully or not.

**Comment by irilyth** [comment]
Reading through the history, the only thing I see is your comment

> I'm going to link in #1312 here so that it doesn't get lost.

If we close this ticket, will #1312 get lost? :^)

Everything else here looks to me like it's been addressed.

**Comment by blackshadowshade** [comment]
I've added #1312 to my milestone, that'll ensure that I don't forget it.  :)

**Comment by blackshadowshade** [comment]
I'll also close this issue. If anyone has any remaining niggles with the game pages, they can open new issues for them.
