### ISSUE TITLE
Can't see full description on Rejected games.

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1766]
Player A invites Player B to a game. Player B rejects the game. (Frowny face!)

Player A now has this game listed in their Rejected Games with the first 30 characters or so of the description, but no way to see the full description.

Perhaps the full description should be in the Rejected table (as it is in the New Games) or perhaps the link to the game should go to a game mat that shows the full description.

**Comment by cgolubi1** [comment]
I think #1731 will address the latter, so if we want to keep this open as a separate issue, let's discuss the idea of the former approach (putting the full description in Rejected Games the way it was in New Games).

**Comment by dwvanstone** [comment]
On the Open Games tab we have the description below the game line. It would be nice if all of the tables related to games had a consistent look.

**Comment by irilyth** [comment]
I think that people probably spend a lot more time on the overview page than the open games page, so I think that (a) it's important that the tables on the overview page look like each other, and don't think it's as important that the open games page match them, because they're on separate pages anyway; (b) if we do want them all to match, I think they should match the current overview page, which (I predict) is what people are used to seeing much more often.

**Comment by dwvanstone** [comment]
I completely agree that having the Overview Page be consistent is a higher priority than having the Open Games be consistent with the Overview Page.
