### ISSUE TITLE
When you cancel a game, include a link to the game, in case you mis-clicked

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1767]
When you create a game, and then cancel it, the "Successfully rejected game" text at the top" should instead say "Successfully canceled Game N", with a link, so that if you clicked cancel by mistake, you could click the link, get the game page, and click something like "create a new game against with the same parameters", much like the "create a new game" follow-up buttons after a completed game. So this would depend on the rejected-game page having some more stuff on it, but once it did, insta-dismissing but linking to that seems good.

**Comment by irilyth** [comment]
I think this can wait for December.

**Comment by blackshadowshade** [comment]
What about using a confirmation popup box instead?

**Comment by irilyth** [comment]
I think that'd make canceling a game somewhat more annoying, in that now it'd take two clicks the vast majority of the time when you *didn't* click it by accident; but I bet that cancelling a game is pretty unusual in the first place.

I don't have a strong feeling about this one. What does anyone else think?

I also think we could wait until the November release goes live, and see what actual prod users think.

**Comment by blackshadowshade** [comment]
We already use the confirmation popup for surrendering games, and the intention there was similar.

**Comment by irilyth** [comment]
> We already use the confirmation popup for surrendering games, and the intention there was similar.

Yeah, but the damage done by accidentally surrendering a round is much greater, and irreversible. If I accidentally cancel a game, I can just re-create it, so I don't think it needs to be as safeguarded.

But if folks are fine with a popup confirmation, I think that's ok too. I still vote for "try it out for a few weeks in prod and see what pepole think, decide for December".

**Comment by dwvanstone** [comment]
This could also be solved by being able to look at rejected/canceled games in the history somehow. I think this is fine as is and can be reviewed again for December.

**Comment by dwvanstone** [comment]
There are two places I found to cancel a game:

  As soon as you create a game, it says "Go to game page". I go to game page and select "Cancel Game". 
  From the Overview page, hit "Cancel" on the game in the New Games table.

In the first case it does not give a message anywhere. (Maybe it should?) In the second case it says "Successfully cancelled game". I couldn't replicate it saying "Successfully rejected game" at the top. Has this been fixed? Or is there another flow that gets it to give the incorrect text?

**Comment by blackshadowshade** [comment]
The wording was fixed in #1749.

**Comment by blackshadowshade** [comment]
Has this issue now been invalidated by #1832, like in #1823, or is there still something to be done here?

**Comment by blackshadowshade** [comment]
I also note that we have #1818, which adds confirmation pop-ups.

**Comment by blackshadowshade** [comment]
So, I'm unsure of how to deal with this issue now. The behaviour after the Dismiss link has been clicked is to autodismiss and redirect away from the cancelled page (in the way that the Monitor preference specifies). That means that there's now no easy way to see the cancelled game.

I wonder if we should remove the autodismiss after cancelling a game.

**Comment by cgolubi1** [comment]
Okay, so rereading this thread:
* irilyth asked for the link message you get when you reject a game to contain a link to the game
* shadowshade suggested a confirm dialogue instead
* irilyth said a confirm dialogue would be overkill
* on a different issue, a confirm dialogue was requested and implemented, and it's now up as a pull request (#1837)

So what i'd say about this issue is:
* If we have confirm dialogues, that's more than enough.  If people lose a game they intended to play, they *can* find it in the History page, or by remembering the number --- they clicked that they wanted to cancel the game, and then they clicked that they were sure.  Maybe they misclicked, but at some point we have to either let people live with the idea that when you interact with UI elements you are stuck with the consequences of having done so, or make the game drag to a halt for everyone else.
* If we decide against the confirm dialogues, we may want to revisit this.

Anyway, that's my take, not irilyth's, but maybe it's a useful starting point.

**Comment by irilyth** [comment]
I stand by "But if folks are fine with a popup confirmation, I think that's ok too." and since we have a popup confirmation now (well, a PR for one anyway), I think that's fine.

Unless anyone else objects, I vote for closing this as fixed by #1837 (or as obsoleted by changes to how the page flow works).

**Comment by blackshadowshade** [comment]
Okay, I'll change #1837 to also fix this issue.
