### ISSUE TITLE
"Next Game" link in the header, and "Next Game" link in game, disagree about how to count pending games

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1788]
For now, this is a placeholder issue for me --- i want to understand this inconsistency before we push and make sure it isn't worse than we think, and i think we should fix it in December.

I don't fully understand it yet, which is why this issue has no details.  I noticed it while trying to reproduce #1771.

**Comment by blackshadowshade** [comment]
I'll link #1738 to this, because that's where the fix for the "Next Game" link in the header took effect.

**Comment by blackshadowshade** [comment]
Okay, I've tracked down the difference, and fixed it in #1787.

The cause is that we have two queries effectively doing the same thing:
- BMInterface->count_pending_games() on line 534 of BMInterface.php
- BMInterface->get_next_pending_game() on line 2239 of BMInterface.php

I've made the two consistent for the moment, i.e., both are now restricted to retrieving only ACTIVE games. Ideally, these two should be refactored so that there aren't two queries, but only the one.
