### ISSUE TITLE
Time & Space and Radioactive interact, but the help text doesn't say so

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1794]
In game http://www.buttonweavers.com/ui/game.html?game=8083, I have a Time & Space die, and my opponent has a Radioactive die, but the  "Interaction with other skills in this game" section of the help text for the skills doesn't mention their interaction.

**Comment by blackshadowshade** [comment]
What interaction are you referring to?

**Comment by jimmosk** [comment]
The Radioactive help text explicitly lists, in the body of the text, those properties that a decaying die will lose, including Time & Space. (Is that not what you're referring to?)

**Comment by irilyth** [comment]
Yep, the fact that a die loses T&S if it decays was what I had in mind. (I thought it did, but wanted to check, and when I hovered over T&S looking for "interactions with skills in this game", it wasn't there.

**Comment by cgolubi1** [comment]
I see, so to put it another way, since the interaction between Radioactive and T&S is described in the body of the Radioactive text rather than being described as an interaction, it shows up if you look at Radioactive, but not if you look at T&S.  So it sounds like part of the description of skills which are lost when Radioactive dice decay should move to being stored as interactions between those skills.

**Comment by irilyth** [comment]
I think copying it to the interactions section would be fine too, since the list has also historically been part of the Radioactive skill description. I feel like the skill descriptions describe the rules for the skill, and the interactions describe things that are consequences of the interactions of rules but which might not be obvious (e.g. if you're looking at T&S by itself). So having this in both places seems best to me. (If it's only in interactions, you'd never see it just looking at the Radiactive skill on its own.)

**Comment by dwvanstone** [comment]
I'm testing this on staging. Here's the text I see with Time & Space: 

"Interaction with other skills:
* Radioactive: Dice with both Radioactive and TimeAndSpace skills lose TimeAndSpace when they Decay"

I thought the intention was for Time & Space to specify that when you capture a radioactive die with a time & Space die that the Time & Space die loses its property when split into two.

**Comment by blackshadowshade** [comment]
So would the following interaction text be better?

"Dice with TimeAndSpace lose TimeAndSpace when they Decay due to Radioactive"

**Comment by blackshadowshade** [comment]
And would we update the other interaction texts relating to Radioactive too?

**Comment by blackshadowshade** [comment]
I'm reopening this issue, because I agree with @dwvanstone that the text doesn't adequately cover the case where a radioactive die is being captured.

**Comment by dwvanstone** [comment]
"Dice with TimeAndSpace lose TimeAndSpace when they Decay due to Radioactive"
"And would we update the other interaction texts relating to Radioactive too?"

I'd say all of the interactions need updating, yes. The text is fine - maybe "when they decay due to attacking a die with radioactivity"? I'm sure what you put in #2316 will be fine. (Thanks!)
