### ISSUE TITLE
How to deal with degenerate games?

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1926]
(I'm trying to pull this conversation out of #1920 and #1603 so we can find it later.)

Since games are not infinite [in terms of number of rounds] the site needs to end a game (even if the players may want to play a degenerate game forever). Also, players may jointly decide that a game is not worth playing and jointly decide to end the game.

I've seen several proposals:

1. Allow a game to end in a draw 
1a Consider a game a draw after N consecutive tied rounds or after N rounds
1b Allow players to agree to a draw 

2. Cancel or delete a game 
2a Consider a game canceled/deleted after N consecutive tied rounds or after N rounds
2b Allow players to jointly decide to cancel/delete a game

3. Use a coin flip to determine the winner
3a After N consecutive tied rounds or after N rounds determine winner with coin flip
3b Allow players to agree to end the game with a coin flip

My favorite of these is the third one because I think it will make tournaments easier to implement later.

**Comment by irilyth** [comment]
I still dispute the premise:

* "Games are not infinite"? Why not? If two players want to play an ongoing game until they both die of old age, why do we have to stop them?
* "the site needs to end a game"? Why? What problem might be caused by a game that never ends?

Why is this problem different from the problem of two players in a five-round game with anime buttons who only ever log in once a year? That could potentially last for decades. What problems would that cause?

Other than a vague aesthetic dissatisfaction with clutter, what problem are we trying to solve here?

**Comment by irilyth** [comment]
> Also, players may jointly decide that a game is not worth playing and jointly decide to end the game.

This one I'm fine with. Of your solutions, I like 6; I don't entirely understand how it's different from 4.

For tournaments in particular, I think the tournament organizer should be able to terminate a stale game. We've talked about that on #1682 -- I still like my https://github.com/buttonmen-dev/buttonmen/issues/1682#issuecomment-155592166 in particular.

**Comment by dwvanstone** [comment]
> Games are not infinite

I don't mean in time, I mean in terms of resources. There is some resource limit on the number of rounds in a game. Am I wrong about that?

I fixed the numbering -- I didn't realize they would be numbered 1-9. I meant them to be 1, 2, & 3.

**Comment by dwvanstone** [comment]
> For tournaments in particular, I think the tournament organizer should be able to terminate a stale game. We've talked about that on #1682 -- I still like my #1682 (comment) in particular.

I wasn't worrying about the case of the idle player for this issue. You're right that this is covered fine on #1682, and I think your comment is perfectly resonable.

**Comment by dwvanstone** [comment]
> Why is this problem different from the problem of two players in a five-round game with anime buttons who only ever log in once a year? That could potentially last for decades. What problems would that cause?

I see no issue in this case. I'm talking about the case where two players are playing a degenerate game where there can be no winner, such as Envy vs. Dead Guy. 

Actually, let me add a fourth possible solution:

4. Leave everything as is
4a. Something bad happens when the resource limit is reached (right now 256 rounds), but real players will proably never actually reach this case.
4b. If players are in a degenerate game they can choose one player to surrender in order to end the game.

**Comment by irilyth** [comment]
Ah, I got it -- this is more like "the code limits games to 256 rounds, what should happen when we get there"? That makes sense.

If so, for one thing I think that the action should trigger off of that in particular -- too many rounds for the code, not too many ties in a row or whatever.

**Comment by dwvanstone** [comment]
> Ah, I got it -- this is more like "the code limits games to 256 rounds, what should happen when we get there"? That makes sense.

Right. Plus I was hoping that whatever happens when the limit is reached can be offered to the players so they don't have to wait to get to that limit if they don't want to.

**Comment by AdmiralJota** [comment]
I think that my preference would be:

* For now, if a game passes 255 rounds without ending, arbitrarily end the game. If one player has won more rounds, they're the winner. If not, add a dummy round 256 whose winner is determined by a coin flip.

* Eventually, also add a way to allow the players to mutually decide to do end a game early, in which case the same process occurs (even if the game hasn't reached 255 rounds). 

I like the fact that, at present, a completed game will always have an actual winner. I'd like it if this were something we could continue to rely on being true in the future. Cancelling it would be my second choice, but it seems like if the players have put that much time and effort into a game, it should have some real closure and not be treated the same as a game that never happened.

**Comment by blackshadowshade** [comment]
I don't understand why there is a problem with games ending in a draw if there can logically be no clear winner. If the game happens to be part of a tournament, then the advancement in the *tournament* can be determined via coin flip, even if the game is drawn. I understand that a coin flip determining the end result is no worse than a one-round Haruspex game, but it still feels awkward and artificial to me.

I dislike games just disappearing, because that could potentially break so many things, so I think that cancelling or deleting games that have already started will be *extremely* difficult to test.

**Comment by AdmiralJota** [comment]
I think it's mainly because we're choosing to either add a special case in this one rare scenario (adding a coin-flip round to handle games that never end) or else adding special cases in who-knows-how-many other places (to handle tied games). 

There are tournaments, as you mention, that will need their own coin flip to compensate for the lack of a winner. There are the changes you're already making on the History page (and I'm not convinced those are the only changes it'll need). There's the Overview page, which will need to reflect the tie when it displays the completed game. There's the Profile page, which displays your win/loss record. Some day we'll have statistics, which will need to be programmed to take into account ties as well. And I'm sure there are other places where we'll need to deal with it that I haven't thought of.

All of this, just to support an extremely rare special case that will hardly ever occur on the live site.

**Comment by AdmiralJota** [comment]
Also, to the "awkward and artificial" point: it may be, but I think it's philosophically consistent with eventually determining initiative with a coin flip. That's also awkward and artificial, but it's the most expedient solution to an otherwise inconvenient situation.

**Comment by dwvanstone** [comment]
I agree that cancelling/deleting games is really not desireable. 

I agree with AdmiralJota that these cases are rare and that we probably don't need the extra infrastructure (coding & testing) to support draws. 

However, as a player, it seems more like other game sites to be able to offer the other player a draw than to offer the other player a "random coin flip which will determine who wins". But I think we can work out the wording so that a coin flip feels like the right way to end an interminable (or degenerate) slog.

**Comment by cgolubi1** [comment]
So, i'm just here because i want to see #1603, which is a bug, get fixed.

To me, a key premise here is: *256 rounds is more rounds than human players will play.  If human players do play 256 rounds (which will literally almost never happen), they will not be surprised to find that they are in a weird state, and will not complain very bitterly about anything that happens.*

So, i don't feel we need a solution for #1603 which is friendly for human players --- it just needs to not be broken.  Therefore, i'm strongly opposed to implementing a "completed but tied" game after 256 rounds, because that needs support from UI elements (like the proposed W/L/T/I in History.js) which are a waste of space in approximately 100% of real games.

Solutions which have been mentioned on this thread which i think would work fine:
* Move a game into REJECTED after 255 rounds - i know Shadowshade thinks this will trigger other bugs, but i think it mostly won't, though i could be wrong.
* Move a game into END_GAME after 255 rounds, and, if necessary, add a fake 256th round with a winner so that the game is no longer tied.

Of those, i'd favor the first mostly because it strikes me as easier to implement and i feel like we should be going for the simplest possible solution here.  But i'd be fine with the second if people like it better for whatever reason.

I am intentionally and stubbornly ducking the problem of how humans get out of a game they are sick of, because i think that is simply a different problem than the database/backend bug in #1603.  And i think all of this arguing has proved that the solutions to those problems are not very similar, so we should stop pretending to believe they are.

**Comment by cgolubi1** [comment]
I guess the point i'd make about human players is that human players can get out of any game by using the game chat to negotiate a player to surrender, and having that player surrender until the game is over.  That's the way it worked on DHS, and it's kludgy, but it will get the job done, works on the site as implemented now, and makes it obvious what should happen with tournaments.  And it's a choice, so if human players want to keep playing until they fall off the edge of the world at 255 rounds, they can (and if we like we can add a message to the action log saying that we terminated the game because the backend only supports 255 rounds, so they know what happened).

So IMO anything we'd want to support for human players has to be much more appealing than the existing "optionally choose a player to surrender using existing tools".  One reason i'm not keen to keep arguing about a solution for human players is that i think we're very far from a consensus on what would be much more appealing for human players than that current, workable, status quo.

**Comment by dwvanstone** [comment]
> Move a game into END_GAME after 255 rounds, and, if necessary, add a fake 256th round with a winner so that the game is no longer tied

I saw this idea earlier, but I wasn't sure about it because I'm not confident on that area of the code. When a game moves into END_GAME how does it determine the winner of the game? Is it simply which player has more rounds won than the other? I just wanted to make sure that setting one fake round is sufficient to determine a game winner on a game that requires three winning rounds.

I think a message in the action log is sufficient for either solution in the rare case that human players ever get there.

**Comment by blackshadowshade** [comment]
The whole thing about "who is the winner" is that the back-end actually doesn't ever know. It only keeps track of whether the game has ended or not. It is the front-end that then displays "Player 1 won" or "Game was tied", based on its internal business logic.

The only thing that I've been trying to do is make sure that the front-end can handle whatever change we add to the back-end gracefully. I really don't want to be adding logging logic to the back-end.

If the game gets changed to REJECTED, we are then giving this game state two possible meanings, which I dislike because one of the meanings isn't really compatible with the word "REJECTED". I'd rather go with BROKEN, if we decide to go that way.

If the game gets changed to END_GAME, then the front-end will need explicit changes to support the display of these 256-round games, even if people will mostly never see the effects of these changes, since we still want to be able to use the Overview and History pages with databases generated with automated testing.

**Comment by AdmiralJota** [comment]
> If the game gets changed to END_GAME, then the front-end will need explicit changes to support the display of these 256-round games, even if people will mostly never see the effects of these changes, since we still want to be able to use the Overview and History pages with databases generated with automated testing.

What changes would be needed?

**Comment by irilyth** [comment]
> The whole thing about "who is the winner" is that the back-end actually doesn't ever know. It only keeps track of whether the game has ended or not. It is the front-end that then displays "Player 1 won" or "Game was tied", based on its internal business logic.

That seems very weird to me, and suggests that different UIs could disagree about who won the game. Am I misunderstanding something here?

Also, won't the backend need to know who won a game for things like stats?

**Comment by AdmiralJota** [comment]
I believe that the front-end universally looks at which player was won more rounds than the other, and we're probably making the assumption that everything will be using that same definition.

**Comment by blackshadowshade** [comment]
The point is that nothing in the backend currently hinges on "who won". This is actually quite a nice thing, because we can then support things like "loser tournaments" without any change to BMGame.

**Comment by blackshadowshade** [comment]
Addressing @AdmiralJota's question about what front-end changes would be needed, basically the answer here is "the minimum that Chaos will allow us to get away with". It would be possible to do nothing at all, but this may break potential QUnit tests of incomplete games that are in the END_GAME state, since it then becomes non-trivial to guess what the Overview and History pages should do.

**Comment by cgolubi1** [comment]
FWIW, i'm happy to help with UI fixes to deal with this case --- however, i do want to note that we've been talking about three different possible solutions, and i've started having trouble following this thread because people are talking about "what will be needed" without talking about which case they're thinking of.  So it would help me if people were a little clearer about this --- i think these are the three distinct logical options we've been talking about (correct me if there are more):
1. Games move into REJECTED after 256 rounds
2. Games move into END_GAME after 256 rounds without any change to the W/L/T state (so they may be tied)
3. Games move into END_GAME after 255 rounds, and win or loss for a fake 256th round is added if needed to prevent ties

Shadowshade, i think you're saying that the only one of these options which is okay with you is 2 (and therefore the UI fixes you've been talking about needing are wrt 2).  Is that correct?

**Comment by cgolubi1** [comment]
I guess one thing that's bugging me is that 1 strikes me as by far the easiest thing to implement.  We had a LONG conversation after the "reject-game" business in which we decided to change "rejected" to "cancelled" internally.  I know we didn't actually mechanically make that change (REJECTED -> CANCELLED) on the backend, but i honestly thought that was just mechanical, and that we were all in agreement that "cancelled" was a better representation of the state.

I don't see why it's a problem that the REJECTED/CANCELLED state "represents more than one thing", because i don't think it does --- i think it represents a game which (1) was created, (2) was not played to the point of determining a winner, and (3) is now over.  That strikes me as describing the situation we want to create when we fall off the DB-allowable number of rounds pretty exactly.  I don't see why it's important to the REJECTED/CANCELLED state that sometime in between being created and being abandoned the game had to transition through START_TURN a few times.  Can someone who thinks REJECTED is a bad match for this use case explain why that's important?

**Comment by blackshadowshade** [comment]
I guess the thing that bugs me is the actual word "REJECTED". I'd have no trouble if we actually made the change to the word "CANCELLED".

**Comment by cgolubi1** [comment]
Sweet!  I move we open a new issue to change REJECTED -> CANCELLED in BMGameState (it's already what the History UI shows, per that previous discussion), and pick that solution.  Who else is in?

**Comment by blackshadowshade** [comment]
Let's do this. Once that change is made, I'll move a game that is at 200 rounds (I want to avoid edge cases here) into the new CANCELLED game state.

**Comment by AdmiralJota** [comment]
Yay, successful diplomatic resolution!

**Comment by irilyth** [comment]
Totally agreed. Yay!
