### ISSUE TITLE
5-digit game numbers causing two-line-high rows on Overview screen

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1955]
Recently the Overview page got a lot less dense, because 5-digit game numbers aren't fitting on a single line, yuk:
![screen shot 2016-02-21 at 11 12 58 pm](https://cloud.githubusercontent.com/assets/6092544/13210386/f8ea0aaa-d8fc-11e5-9f7d-ce5645b2b3be.jpg)

**Comment by cgolubi1** [comment]
Hey, look, Jota, someone in the world uses a narrower browser window than i do!

More seriously: do we need the word "Game" in each entry in this column?  We could just go with "View 10399", "Play 10401", "NEW 10402".  Or maybe "10399 (View)", "10401 (Play)", "10402 (NEW)".

**Comment by blackshadowshade** [comment]
I'm happy to lose the word "Game" here, since it's already in the column header.

I don't have a strong preference for either of the options that Chaos has mentioned, although I think that perhaps the first might be better, since for me, the game number itself is less important than whether the game is a new game or an active game.

**Comment by dwvanstone** [comment]
> I don't have a strong preference for either of the options that Chaos has mentioned, although I think that perhaps the first might be better, since for me, the game number itself is less important than whether the game is a new game or an active game.

Agreed. "View 10399" would be fine.

**Comment by irilyth** [comment]
I agree that dropping Game is fine, and also like the first option better.
