### ISSUE TITLE
Art for 50 States set

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1961]
It'd be cool to have some art for the 50 States set. Three possible sources:

* If we don't mind non-round images, we could use state flags.
* If we prefer round images, we could use state seals, or the backs of state quarters.

The flags are probably slightly more recognizable, and are surely in the public domain. The quarter designs seem to be public domain as well, with some caveats that we could investigate if we decide we like those. I don't know about the state seals, and think they're the least cool option, unless we prefer round and don't like quarters (or they turn out to have a problematic or complicated copyright status).

**Comment by jimmosk** [comment]
I definitely vote for round, to be consistent with everything else and be true to the Button aspect.  But I think circular versions of the state flags (just crop a circle from the center) would work just fine, so we needn't eliminate that possibility.
I lean towards state quarters, because I think that's the most widely recognized of these options.

**Comment by irilyth** [comment]
Another nice feature of the quarters idea is that they'd be pretty visually distinct from everything *else*. It's cool when sets have a consistent art style (when that makes sense).

**Comment by blackshadowshade** [comment]
Here's a suggestion by Kaori:

[20states.pdf](https://github.com/buttonmen-dev/buttonmen/files/160628/20states.pdf)

**Comment by blackshadowshade** [comment]
Personally, I think these look great!

**Comment by blackshadowshade** [comment]
And here are the other 30 states.

[30states.pdf](https://github.com/buttonmen-dev/buttonmen/files/162278/30states.pdf)

**Comment by blackshadowshade** [comment]
So, Kaori would like discussion on what you like and what you don't like. Some things that's she's mentioned:
- whether it's okay that she's slightly changed wording or shapes
- whether the white circles are the right size
- whether you like the images being off-centre
- what you think about the font
- whether the wording should be straight or bent
- whether each button needs a separate name when it's obvious in the image

**Comment by AdmiralJota** [comment]
Could you give some examples of what you're referring to by wording or shape changes?

**Comment by AdmiralJota** [comment]
From in-game chat with Kaori:

> I've erased lots of wording (state names, dates, motto or whatever) where it was just the plainly written letters because I thought it irritating on the image (i.e. Delaware, Illinois).
> Where the wording is part of the image I've kept it. Except Arkansas and California but I'm not happy with these and would prefer to replace at least CA's name with the usual font.
> 
> Shape changes were even smaller:
> I had to enlarge top and bottom in NC, TX.
> In TE I pulled the right more to the center to have it more compact.
> OH has blue sky as a background for the funny shaped flag.
> And RI, WV, WY borders aren't round but square.

I think all of that is fine. They're not exactly the state flags *as* button images; they're button images that are closely based on state flags. Which seems like an pretty reasonable artistic choice.

Off-centering the art makes sense, given the die circles. And it's hard to tell if the circles are big enough without numbers in them. They're *probably* OK, but it wouldn't hurt if they were a bit bigger.

I think that having the button name in a relatively consistent place on the button is a good idea, regardless of whether or not it happens to appear inside of the art as well. And I think the non-curved names looks OK here. But I'm not a huge fan of this particular font, personally.

**Comment by blackshadowshade** [comment]
Kaori has sent me three more images, so that the other suggestions for images might also be discussed. She mentioned that the third image is a lot more work than the other two, and that she's not sure how to deal with multicoloured flags.

![al_coin](https://cloud.githubusercontent.com/assets/2898401/13620179/f53dda02-e5e1-11e5-9f28-6719fe710dc6.png)
![al_flag](https://cloud.githubusercontent.com/assets/2898401/13620180/f5521576-e5e1-11e5-834a-ac365989c482.png)
![al_mixed](https://cloud.githubusercontent.com/assets/2898401/13620181/f59f0e76-e5e1-11e5-836f-f6c3d0874716.png)

**Comment by blackshadowshade** [comment]
I personally think that the image with the coin is too busy for a button, and I much prefer the simplicity of the flag design.

**Comment by AdmiralJota** [comment]
I agree; the flag-based ones work better than the coin-based ones.

**Comment by irilyth** [comment]
I think the flags look great; the quarters are ok too, but I think the flags are nicely similar but much more distinct from each other than the quarters.

Some comments about Kaori's previous questions, which may be moot now, but hey:

> whether it's okay that she's slightly changed wording or shapes

I think that's totally fine.

> whether the white circles are the right size

I agree that we should see how they look like with numbers in them. In general, they should be about the same as the circles on the other buttons, right?

> whether you like the images being off-centre

Sure, I think it works fine.

> what you think about the font

I agree that the font is a little too playful. Something bland and sans serif seems good.

> whether the wording should be straight or bent

I don't think that matters, and it's good to do whatever fits with the art -- if curving the name around some of the art looks good on one particular button, go for it, and it's fine if they're not all consistent.

> whether each button needs a separate name when it's obvious in the image

I think it's nice to have the button name on there, even when the name already appears elsehwere on the image, but don't feel strongly about it, and in line with the "the name doesn't have to be the same on all of them" principle, if in any specific case you think it looks better without the name, try leaving it off and see if anyone disagrees.

**Comment by blackshadowshade** [comment]
And now versions with different fonts:

![nd_fonts](https://cloud.githubusercontent.com/assets/2898401/13660164/85da8d22-e6db-11e5-97f3-bccfe81e85c1.png)
![il_fonts](https://cloud.githubusercontent.com/assets/2898401/13660166/8608f112-e6db-11e5-810f-9320aca9778c.png)

**Comment by blackshadowshade** [comment]
I've always been a fan of the original, Helvetica, and it still looks great!

**Comment by AdmiralJota** [comment]
My favorites out of these are Helvetica and Tahoma. They all look good, though.

**Comment by dwvanstone** [comment]
I love the idea of the coins as artwork, but I agree with everyone that they're visually too busy. I really like how the flags are coming together. 

As to fonts, Arial and Helvetica are my favorites. Maybe kaufman has an opinion?

**Comment by kauftaxman** [comment]
To my eye, the Verdana looks best for the state names (I like the serifs (?) on the capital I) and the spacing makes the reading clearer.  For the dice, I like the Helvetica.  Thin, sleek and clear.

As for the pictures, just as its standalone flag, the New Mexico looks particularly awesome!

**Comment by Hurtay** [comment]
Ok, so I created my own account now...
Verdana and Tahoma are not completely "sans serif". I didn't realise this when I choosed them as possible fonts. And we wanted to use a font without serif so it looks more official, like a font the government could use. That's why I like the classic Helvetica better for this set. 
I've tried a few more with Helvetica to see how it turns out. I've chosen a state beginning with "I" again on purpose. Here is the result. I like it. What do you think?
/Users/Ute/Desktop/BM Zodiac/50 States/Ute/_zur Abstimmung/6er-Entwurf.png

**Comment by irilyth** [comment]
I don't think the "must be purely sans serif" part is super important; I looked at a couple of state government web sites, and noted that they all used plain sans-serif fonts (as opposed to full serif fonts), but in fact I didn't check whether they had serifs on the capital I and stuff like that.

I think all of them look fine, and I think that if others prefer Tahoma, the serifs on the Is aren't a reason to avoid it.

**Comment by Hurtay** [comment]
So far we've got votes for
- Helvetica
- Helvetica / Tahoma
- Arial / Helvetica
- Verdana / Helvetica
- Helvetica

That's why I've decided to try some more Helvetica.

**Comment by blackshadowshade** [comment]
I've just noticed that the button images are starting to look a bit diamond-shaped to me instead of circular.

**Comment by AdmiralJota** [comment]
As for the size of the circles with the numbers in them: _if_ making the circles bigger would let us make the skills more legible, then there might be some value in making them bigger. But if it's not going to help much with the skills (and I doubt it will), then I think this size looks good.

**Comment by jimmosk** [comment]
blackshadowshade commented:
> I've just noticed that the button images are starting to look a bit diamond-shaped to me instead of circular. Maybe shave off a little at the four corners?

I concur -- it's especially noticeable with West Virginia.

**Comment by Hurtay** [comment]
Yes, I've noticed that, too. Funny enough... I've always used the same template. I'll look into it.
And for the number circles: every one with a digit in is already the slightly bigger size.

**Comment by Hurtay** [comment]
Using your advices I've finished half of the playable states buttons tonight. For the states beginning with the letter "I" I've chosen a different font for the name (Verdana), everything else is Helvetica. 
And I'd say I've got the images round again, do you agree? Due to the light reflex and shadow it still looks slightly diamond shaped but that's just an optical illusion, I've checked it. Here something for you to look at. 
![image](https://cloud.githubusercontent.com/assets/17772027/13719026/6c8d2062-e7f0-11e5-8d4e-4a21606dd1e8.png)
As soon as I've finished the first 34 I'll send the image files to bss to create a pull request? The non-playable 16 images will follow.

**Comment by blackshadowshade** [comment]
Okay, I'm closing this issue because #1968 added all the images.
