### ISSUE TITLE
Add "Jolene" Rare Promo BM

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1997]
Rare BM, exclusive to the Lord of the Fries Kickstarter:

![7fe5738b8f8c8ed3ca7f5bf1dc37b774_original](https://cloud.githubusercontent.com/assets/5848173/15402181/ca384902-1dc0-11e6-9f92-66f907c7cc1a.jpg)

See: https://www.kickstarter.com/projects/cheapassgames/lord-of-the-fries/description

**Comment by blackshadowshade** [comment]
So, there are two things that need to be done here:
- we need to button-ify the Jolene image
- we need to get the button flavour text

**Comment by Hurtay** [comment]
If no one else is keen on the job I can look at the image part as soon as I get a spare moment. It might take a while to get the image done so be patient with me (or do it yourself).
The flavour text hopefully comes with the cards. Does anyone we know back this project?

**Comment by AdmiralJota** [comment]
Ah. So that is the slightly embarrassing bit: I am pretty sure I own this card. However, I cannot remember where I put it.

I shall continue searching, but if we find anyone else who has it and _hasn't_ misplaced it...

**Comment by irilyth** [comment]
The flavor text should be "I'm begging of you please don't take my man", or possibly "I'm begging of you please don't take my twenty-sided Speed die".

**Comment by Hurtay** [comment]
Instead of a real buttonifying (is that a word?) I just pasted the image into my template. I'm not as unhappy with the result as I expected to be so I present Jolene to you already.

![image](https://cloud.githubusercontent.com/assets/17772027/15612093/a5ecf0b6-242d-11e6-98a0-4d6825db86ba.png)

And because it's always nicer to have more than one button in a set ("Lord of the Fries"?) I did the same for Kublai even if it's exactly the same recipe as his soldier self. Are there more buttons hidden in the game or is it just these two I found in said kickstarter?

**Comment by blackshadowshade** [comment]
So, were there any more buttons in this Kickstarter?

**Comment by AdmiralJota** [comment]
Just Jolene and the new Kublai image. I found my card, and it turns out Jolene didn't come with any flavor text, alas.

**Comment by TheOrgg** [comment]
Should she be in the same Promo/Rare set as Mutton Ben?
