### ISSUE TITLE
have opinions about RandomBM*Skill

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2007]
RandomBMMonoSkill - RandomBMPentaSkill have been released to the dev site.  Have opinions about them and improve them as needed before releasing them to prod.

**Comment by AdmiralJota** [comment]
I have opinions! Several of them, in fact.

Starting with a comment from @irilyth:

> Yeah, I think my goal [...] was to make Duoskill and Triskill fun, Tetraskill borderline, and Pentaskill crazy enough that no one would say "why did you stop with five".

At the moment, I think that TriSkill is borderline and TetraSkill is that crazy, so I am in favor of scaling things back slightly. 

**One issue is that the dice are quickly winding up with big pileups of skills.** The current algorithm is:

>  - Monoskill: 1 skill, appearing a total of 2 times on various dice.
>  - Duoskill:  2 skills, appearing a total of 5 times on various dice.
>  - Triskill: 3 skills, appearing a total of 7 times on various dice.
>  - Tetraskill: 4 skills, appearing a total of 10 times on various dice.
>  - Pentaskill: 5 skills, appearing a total of 13 times on various dice.

I'd suggest that instead of 2/5/7/10/13, we try targeting something closer to 2/4/6/8/10. That should slightly reduce the average number of skills per die, as well as reducing the number of dice that wind up having every (or nearly every) available skill on them.

**Another issue is that it's not at all unusual for the same skill to wind up on 4-5 dice.** This is sometimes not a big deal, but other times it can render a button more or less completely broken. (E.g.: four Null dice or four Time and Space dice.) I know that the current algorithm makes it less likely for a skill to wind up on 4-5 dice than on 2-3 dice, but when you have TriSkill vs. TriSkill, that's six different skills we're allotting, and even "less likely" things get a lot of opportunities to occur.

For this, I'd suggest changing the probabilities to something more like (for example) a 10.5% chance of a skill appearing on one die, an 80% chance of it appearing on two dice, an 8.5% chance of it appearing on three dice, a 1% chance of it appearing on four dice and a 0% chance of it appearing on five dice. 

(The reason I suggested those particular probabilities is because they make it so the _average_ number of dice each skill appears on is two. If we use those probabilities (or different ones that averaged out the same), we wouldn't need to explicitly enforce the 2/4/6/8/10 rule: things would just tend to average out that way on their own.)

**A third issue is that it appears we're still excluding Doppelganger, Morphing, Radioactive and Fire from the list of skills.** Is there any reason we still need to be doing that? I think that particularly the Tri+ buttons would be more fun if there were a wider range of skills to draw from, since they'd be less repetitive.

**Comment by cgolubi1** [comment]
> A third issue is that it appears we're still excluding Doppelganger, Morphing, Radioactive and Fire from the list of skills. Is there any reason we still need to be doing that? I think that particularly the Tri+ buttons would be more fun if there were a wider range of skills to draw from, since they'd be less repetitive.

Yeah, so basically there's a set of "non-excluded skills" which all the RandomBM buttons use.  Our plan is to add things to that set over time, but after doing enough testing to make sure we're not going to be throwing internal errors at players by doing so.  So if you want to nominate your favorite next skill to be added, we can work on starting to test it, but that's somewhat orthogonal to defining these new buttons --- when we add Radioactive as an option, it will be added as an option for all of these new RandomBMs as well as for Mixed.

**Comment by AdmiralJota** [comment]
Yeah, this is where I got that list that I mentioned from:

        protected static function excluded_skill_array() {
            // Actively exclude possibly problematic skills
            // The current selection is conservative, and should be whittled down in time,
            // after we deal with bugs that arise from strange skill combinations
            return array(
                'Auxiliary', 'Reserve', 'Warrior', // game-level skills
                'Doppelganger', 'Mad', 'Mood',
                'Morphing', 'Radioactive', // recipe-changing skills
                'Fire', // skills that add an extra step to attacks
                'Slow', // skills excluded because they're no fun
            );
        }

But it seems like we've already tested lots of skill combinations since this list was originally written (just look at the 50 States), and I was wondering if this PolySkill release would a good time to pare it down.

In fact, if we pushed a "whittled down" selection out to the dev site now-ish, then we could test them as a part of the PolySkill testing, since TetraSkill and PentaSkill would provide a good opportunity for us to spot any bugs that arise from the "possibly problematic" skill combinations.

**Comment by irilyth** [comment]
My two cents:

1. I'm inclined to agree that we should drop back to 2N.
2. While we're at it, we should balance the skills, such that each skill appears on two dice.
2a. Or, at most three, if we want more variety. But I'm pretty fine with saying that Polyskill in general is "N skills, each on two dice".
3. I think it's time to enable more skills for RandomBM, but I'd rather do that next month, so we can focus on getting the spec right for RandomBM Polyskill in the next few days. Let's spend June testing the heck out of some more skill combinations.

I'm happy to test a little more first, but I'm also pretty happy to say that we've seen enough, and should go straight to 2N and spend another few days testing *that*.

**Comment by AdmiralJota** [comment]
I'd agree with going straight to 2N and testing that now.

**Comment by AdmiralJota** [comment]
(And I am not opposed to making it just "N skills, each on two dice" -- it's certainly less complicated than my proposal.)

**Comment by blackshadowshade** [comment]
Okay, I'll work on getting a pull request up as soon as I can.

**Comment by dwvanstone** [comment]
I'm finding it takes time to parse buttons with "spt" versus "pts" versus "tps" which turn out all to be the same. Could we sort the skills in some standard order?

**Comment by AdmiralJota** [comment]
I haven't actually tried it, but I bet that we could probably do that by just changing the last line of randomly_select_skills() in BMBtnSkillRandomBM.php to:

    return sort(array_keys($skillArray));

**Comment by Hurtay** [comment]
Here my two cents about what I've played so far:
- In general I think reducing the skills to two dice each is an improvement. It was too chaotic before, especially with the tetra- and pentaskills.
- Is there a chance to have the reverse game of what you've just finished? I mean not a game with other random buttons but with exactly these two buttons, just the other way round?
- Another idea is to choose one or some of the skills to create your random button with. I know it's a different topic, just wanted to ask if that's an idea to keep in mind?
- Do we mind nonsense combinations like focus and rage/trip/slow? Or do we only look for bugs? How about Berserk/stealth?

**Comment by blackshadowshade** [comment]
point 2: #1623.
point 3: the idea hasn't been raised specifically, although #344 might be one way
point 4: no, we don't mind, we're looking for bugs, and incompatible skills should still work consistently (for some level of consistent)

**Comment by jimmosk** [comment]
Right now a challengee is only told they'll be playing with a "RandomBM[something]skill" button when they have to choose whether to accept or reject the challenge.

Given that some skill combinations would result in such a lopsided battle that the challengee might not want to play with it, why not generate the random button as soon as the challenge is made, so the challengee can be shown that information when deciding whether to accept or reject the game?

**Comment by irilyth** [comment]
#1750 is similar to jimmosk's suggestion, in the other direction, suggesting that if you select "give me a random button", it should *not* show you what button you're going to get before you accept the game. My suggestion is still that it should be a game-create-time checkbox, so you can get whichever behavior you prefer.

I think it'd be fine to have that option for RandomBM too. Maybe open a new issue for that? I don't think that's an improvement we can realistically make by the June release, and I don't think it should block the RandomBM Polyskill buttons from going out in the June release.

**Comment by AdmiralJota** [comment]
I personally prefer the surprise of not knowing what either player is going to have until the game starts. But I think that making it a create-time option is a good idea.

**Comment by AdmiralJota** [comment]
> Another idea is to choose one or some of the skills to create your random button with. I know it's a different topic, just wanted to ask if that's an idea to keep in mind?

This is also kinda similar to (although not the same as) #2006.

**Comment by irilyth** [comment]
> My suggestion is still that it should be a game-create-time checkbox, so you can get whichever behavior you prefer.
>
> I think it'd be fine to have that option for RandomBM too. Maybe open a new issue for that?

Done! #2016.

**Comment by irilyth** [comment]
Skill-selection for RandomBM is sort of like #2006, but not really -- if it turns out that the skills you want happen to be the skills used by a set-based RandomBM, that's great, but I think being able to pick and choose skills at create_game time is a whole different ball of wax.

**Comment by irilyth** [comment]
In particular, implementing everything on #2006 won't get you any closer to being able to pick and choose at create_game time -- they're similar from a player point of view, but the work involved, from a dev point of view, is totally different, right?

**Comment by AdmiralJota** [comment]
Yeah, they're totally different implementation-wise. But from a player experience point of view, there's some (admittedly limited) overlap if the skills you're interested in playing with happen to match one of the sets we're emulating.

**Comment by irilyth** [comment]
Yep, and the target audience for #2006 is definitely people who might say "I like this set, but I've played all the buttons in it a zillion times, I wish I could get more buttons with the same skills and general shape of the buttons in this set".

**Comment by Hurtay** [comment]
I'm playing a lot with newbies these days and they don't know the sets. They know what skills they like and they ask me for another game with speed/berserk/warrior/konstant* dice without introducing any new skills at the same time. And they don't like just one skilled die for each button because that's usually taken in the beginning and then it's just plain buttons. Instead of creating the same combinations over and over again I would love to do that via RandomBM with one or two of the favourite skills.

(* take your pick)

**Comment by irilyth** [comment]
I've created #2020 for the feature idea of limiting at create-game which skills you'd like a RandomBM to have.

**Comment by cgolubi1** [comment]
So, i see lots of wish list items on here, which is great, keep 'em coming.

Anything that's a blocker for the June release that we haven't addressed yet?

**Comment by irilyth** [comment]
I don't see any blockers here. I think sorting is good, and 2N is good, and the other things people have asked about are all on other tickets at this point, except for the nonsense-combinations one, which I think we haven't really agreed is necessary (but if anyone thinks it is, make a ticket).

**Comment by cgolubi1** [comment]
It'd be great if we could close this one out; anyone willing to poke through the comments and see what needs to be spun off into other issues?

**Comment by AdmiralJota** [comment]
I looked through and only saw one thing that didn't have its own issue (enabling more of the excluded skills), so I created #2067 for it.

I think this can be safely closed now.

**Comment by cgolubi1** [comment]
Thanks, Jota!
