### ISSUE TITLE
Log says Turbo die changed size when it didn't

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#2217]
In http://www.buttonweavers.com/ui/game.html?game=24235 I made an attack with a Turbo (Z=8)! die, and typed nothing in the box for a changed Turbo size.  The game correctly kept it at 8 sides, but the log reported it this way: 

> jimmosk performed Power attack using [(Z=8)!:6] against [(X=20):5]; Defender (X=20) was captured; Attacker (Z=8)! rerolled from 6, changed size due to turbo

> Turbo die (Z=8)! remained the same size, rolled 5

(because the log is reverse chronological order, that second message is actually above the first, but I switched the order to read more clearly here)

Can that spurious "changed size due to turbo" be removed?

**Comment by blackshadowshade** [comment]
So, what do you all think? Do we remove "changed size due to turbo" always? Is it really necessary?

**Comment by dwvanstone** [comment]
Maybe a quick change would be to add the word "possibly" before the word "changed". The next line says what happens. 

Or, why have that text (", changed size due to turbo") since the next line also gives that information?

It's not quite right as it is, but I'd go for a quick text change over a logic change.

**Comment by blackshadowshade** [comment]
I'm fine with either solution, and my preference would be to remove the "changed size due to turbo" altogether.

**Comment by dwvanstone** [comment]
Agreed. I don't think that text is needed.
