### ISSUE TITLE
Total count on history page not symmetric

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2238]
Go to the History page. 

Search for the history where Button A = Washington and everything else blank. The total stats in the bottom right reads: 20/58/12.

Search for the history where Button B = Washington and everything else blank. The total stats in the bottom right reads: 59/19/12.

These should be consistent. 

(The difference comes from a single Washington v. Washington game which player A won on both of the history pages.)

**Comment by cgolubi1** [comment]
Interesting.  The error must be in the summation:

Exactly the same 92 games are reported by each side, and tmpfile0 (the "A column" version) says 20/58/14, while tmpfile1 (the "B column" version) says 59/19/14:

```
leocrotta,[~],22:18(0)$ grep "^Game" tmpfile0 | awk '{print $NF}' | sort | uniq -c
   4 Cancelled
  78 Completed
  10 Progress
leocrotta,[~],22:20(0)$ grep "^Game" tmpfile1 | awk '{print $NF}' | sort | uniq -c
   4 Cancelled
  78 Completed
  10 Progress
leocrotta,[~],22:20(0)$ 
```

So those all add up correctly.  Hmmm... 
```
leocrotta,[~],22:22(0)$ grep "^Game" tmpfile0 | grep Completed | grep -v '(3)'
Game 18121      kusinohki       Washington      Fingle  Qcpu    2016-11-21      2017-01-06      2/5/0 (5)       Completed
leocrotta,[~],22:22(0)$ 
```

Maybe i'm just pushing buttons randomly, but that makes me suspicious.

Nope, that's not it - Fingle also has exactly one game with a victory condition of other than 3 wins, and there we get:
```
24/39/11
39/24/11
```

Okay, but that definitely tells us it's something special about one of the Washington games that's getting things mucked up.  (And hold the thought about the 5-win game, because after all, Fingle *won* that game and Washington lost it.

Enh, unclear, might be a red herring.  Incidentally: Washington won 20 games.  So the report when Washington is the A player is correct, and the report where Washington is the B player is crediting Washington for one game too few.  BTW, in `BMInterfaceHistory`, the query for the summary is totally separate from the query for the games.  So it's not surprising that one would be broken and the other wouldn't be.

More later, i'm sure.

**Comment by AdmiralJota** [comment]
I don't think it's an *error* per se. It's just an oddity, and I'm not sure what the best way to handle it would be.

Neither search result is crediting *Washington* with any number of wins: they're crediting Player A and Player B with wins. 

It's just that in the first set of search results, most of those games are oriented so that the player playing Washington is A and the player *not* playing Washington is B. And in the second set, it's vice versa. 

But the game where *both* players play Washington is an exception. It could be listed either way around (with the player who used Washington and won as Player A or with the player who used Washington and lost as Player A). In this case, it happens to be listing the player who used Washington and won as Player A in both lists, and the player who used Washington and lost as Player B in both lists.

**Comment by cgolubi1** [comment]
Good call, Jota.  That must be it.  Devious: anything particular that you can think of that should be different here?

**Comment by irilyth** [comment]
This probably isn't a bug if the intention of the history API is that it's only showing records for players, not buttons. I hadn't really assumed that, but I suppose it makes sense.

I wonder if it'd be better if the history API were button-centric if no players were specified. It would mean that http://www.buttonweavers.com/ui/history.html#!buttonNameA=Washington&buttonNameB=Washington would say that the overall record was 1/1/0, which seems vaguely weird. Hmm.

Maybe it doesn't matter if the history API is player-centric, and people can just use the forthcoming stats API to get button-centric info.

**Comment by AdmiralJota** [comment]
I think that, most precisely, it's *game*-centric. It's just that A) games are more between two players than they are between two buttons, and B) you're not allowed to have the same player on both sides in a match (or else we'd run into this same problem there).

Given that, is there any way to handle this sort of thing that *wouldn't* be weird?

One argument might be that if you're searching by button, games where it's playing itself could be listed as ties. But then on the other hand, it seems weird that the same game would be treated differently depending on whether or not you happened to include a player name in your search parameters.

**Comment by dwvanstone** [comment]
> Good call, Jota. That must be it. Devious: anything particular that you can think of that should be different here?

I think I just have to change my expectations. I think the history table is excellent as is and I wouldn't change a thing. I think the forthcoming stats API is the place for me to get button stats. 

Thank you all for investigating this! Can I close this as not-a-bug? (Is that "wontfix"?)

**Comment by blackshadowshade** [comment]
Closing this, in accordance with @dwvanstone's wishes.
