### ISSUE TITLE
New Peloton button set

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2360]
AnnoDomini is interested in creating a new set of buttons based on cycling:

http://buttonweavers.wikia.com/wiki/Sets/Peloton

He's looking to get these on a dev site for testing.

**Comment by cgolubi1** [comment]
In particular, as a cyclist, a BM dev, and someone who spends a lot of time complaining about gender representation of fictional characters, i'd like to raise the issue of all the proposed Peloton buttons having (afaict) male names, and ask if this is something we could address.  If we're bringing buttons from a particular existing canon, then what's in that canon is what we get, but if we are making up our own buttons, we have more flexibility and IMO we should use it.

A little bit of googling suggests that these button names most likely come from: http://ocm.wikia.com/wiki/AnnoDomini but (1) i'm not a racer, and i don't know anything specifically about OCM or that particular (presumably?) fictional team, and (2) i don't know why AnnoDomini picked those buttons in particular.

If you've been talking to AD about this via e-mail, feel free to add me to that thread and i can raise my request there.

**Comment by AnnoDomino** [comment]
Hi All,
I am happy to clarify on all the above points.

1) OCM is an online cycling management game which runs for around 10 years now. It was a private project of one guy from Denmark which rose up to one of the best cycling manager games available online. I am part of it since 2011 and run a team called, no surprise there, AnnoDomini. I had some success, been in top 20 in the world for some time, now I am placed 62nd out of around 900 players classified.

2) Here in Buttonmen I would love to create my own set of buttons. When I thought about what theme would fit best here I thought about cycling, as this is one of my bigger passions. I remember Glassonion that we used to chat about cycling one time during a game. I am not a professional racer, but I do take part in amateur races. So I thought that a few buttons of cyclist racers would be a nice addition to the game. 

3) In cycling there are different types of riders, each of them needs to posses different skills, so I thought that each button would represent a different type of rider. Initially I thought to simply name buttons by the rider type, ie Climber, Sprinter, ect but then I realized that most of the buttons on the site have some personalities, so maybe it is better to give them some names. I obviously cant use real life rider names, so I thought about using my fictional riders from my team in OCM to help come up with some names. I also payed attention not to repeat any names which are already used in the Buttonmen. Those are simple first names which are given to many people in the world, so no issue with any copyrights there I guess :-)

4) The next thing I was concerned about is button art. I also wanted to be 100% sure I dont break any rights here so I decided I can try to draw myself some cyclists. I took a piece of paper, a pencil and drew 7 coloured pictures. I am not an artist myself, cant paint/draw well, but I shared those drawings with Kaori and she more less liked them. I am of course open to any suggestions here, if anybody feels the drawings are too bad  quality in comparison to other button art to be put on the site then let me know, I can try to figure out sth else.

5) As it comes to gender - I am open for all suggestions here. The thing I fear most is that I am not sure I will be able to draw a nice picture of a female cyclist. But of course I can try. It would also need to be decided which of the 7 rider types would be female cyclist and which male - the 7 types I wanted to create are described in the wiki page
http://buttonweavers.wikia.com/wiki/Sets/Peloton

Kind Regards
AnnoDomini

**Comment by cgolubi1** [comment]
AnnoDomini: thanks very much for the detailed comment!  I read the wiki earlier, and i really like the concept for the set and am very keen to try it out!

I'm pestering a randonneur friend of mine for a couple of historical or fictional female cyclist names (it sounds like you just made up the names for your OCM cyclists, though, so we can probably make these up too if we can't think of anything good), and i'll owe you suggestions for which of the riders to sub, but if you have thoughts, you should say too.  (I don't want to suggest subbing out your favorite rider name.)

I think your first draft art on the wiki looks great!  Nice and colorful, and it should be a style which is somewhat distinctive for this set.

**Comment by AnnoDomino** [comment]
What we could also do is leave the 7 buttons as they are and just add one or two more - a female cyclist on a mountain bike for example, if we want not only to have a variety of gender but also a variety of bike types ect.
But the real challenge in drawing remains. If you look at photos from women cycling road races, in many cases you will not be able to quickly tell at the first glance if certain cyclist is a man or a woman. The siuts and helmets make it difficult to judge. Usually a closer look at the face would clarify this, but this brings me back to my drawing skills - I am very bad at faces and I am not sure if I have skills to reflect the subtle differences between man and woman face lines...

**Comment by cgolubi1** [comment]
Hmm.  Anything i can do to offset the concern about the drawing?  Based on what you've said, it sounds to me like it shouldn't be a big deal --- the new cyclists' images won't be very different, so it shouldn't be too hard to draw them.  I'm not particularly concerned about whether the art looks visibly female, but if you are, you can always take the Randall Munroe quick fix of "add a ponytail" (which is not unrealistic --- a lot of female athletes wear ponytails.  In the U.S. women's hockey league, which is my actual spectator sport of choice, they put the players' names below the numbers on the jerseys rather than above, so long-haired players' names would be visible).

Apropos of nothing: just glancing at the recipes, i'd be tempted to suggest making Doyle's handicap bigger - make it an o(20) instead of an o(10).  T&S and Maximum are both pretty powerful on otherwise balanced buttons.  But that's just a wild guess --- we'll learn more in play testing.

I don't know anything about bike racing, but it's fun to speculate about buttons: how would a mountain bike be different skills-wise?  Maybe some aggressive skills like poison or berserk on the wheels?  If we add a randonneur, she should clearly have a spare (reserve) wheel, and some reserve time & space or focus.

**Comment by irilyth** [comment]
I agree that the art doesn't have to be tremendously different, and that a ponytail isn't a bad idea, although of course not all people with ponytails are women. :^) Using a traditionally feminine name for the button, and she/her pronouns for the flavor text, seems like it'd also help.

**Comment by AnnoDomino** [comment]
Thanks for the advice - long hair is indeed a good idea :-)
Here is what I have come up with: as in women cycling riders do not specialize that much in one particular area, when they are strong, then they win on every terrain, then I would keep the more specialized roles like climber/sprinter/TTer within male riders and assign more flexible roles to female atheletes.
I have also come up with the 8th rider type which is a lead out. I will describe it on the wikia page. 
We would then have 2 female riders (Puncher, Break Away rider) and 6 male riders.
Hope that would be ok.
Now time to get back to the table and draw some female riders... It may take a while so please give me some time with this.

**Comment by cgolubi1** [comment]
AnnoDomino: your proposal sounds awesome!  I really appreciate your taking the request and running with it, and i'm looking forward to trying this set out.

Playtesting: once we have an initial set of recipes nailed down, shadowshade will submit a pull request containing them, and we'll stand up a one-off dev site containing the new button set.  Button art isn't a prereq for standing up the site, though we'll include whatever is available so playtesters can look at it.

Then playtesters (the dev team, you, anyone else who wants to create an account on the dev site) can login and play whatever games they want with the new buttons as if they were a normal set.  Usually everyone has their own algorithm for what they want to test --- if you want to create games matching what you suggested above, that can probably work.  As you tweak the recipes, we update the dev site, and when you say they're good to go, we push them to go to the production site.  As long as the initial proposed set is reasonable and we fix any site logic bugs introduced by the new recipes (i.e. skill combinations we've never tried before that turn out to have a problem, which probably won't come up with your set, but one never knows), it's your call when you think the recipes are ready.  We can do as much or as little balance-tuning as you want.

Jota might have some useful stuff to say about what criteria worked well for him, since he just went through a round of balance-testing for the Steven Universe buttons.

**Comment by AnnoDomino** [comment]
The wiki is now updated with 2 additional buttons - Julia and Timea. Please let me know if they are ok.
I was speaking to Kaori and she suggested the following next steps:
1) I will work on ths drawings to add Names to each button. Did that for Orlando only so far (image updated on the wiki). 
2) Once all buttons have names I will send them over to Kaori who will re-size them to format uploadable to the site
3) When she has this completed, then I need to raise a request (here?) to get the dev site created.
4) Then we begin testing.
5) Only when testing is completed and we agree on button receipes, the receipes will be added to the buttons art (dont know how I will do this yet, but I guess I have time to figure it out).

Please let me know how does it look from your pserpective.
