### ISSUE TITLE
Time and Space die skill needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#263]
Time and Space: ^
Time and Space die appear within a triangle or pyramid.
- - - - - - - - - -
Time and Space Dice were created for the Looney Labs Button Man, Tirade. They are represented by a "^" before a die. If a Time and Space Die is rerolled after it participates in an attack and rolls odd, then the player will take another turn. If multiple Time and Space dice are rerolled and show odd, only one extra turn is given per reroll.

 Clarifications: •^o (Time & Space Ornery): Will only get an extra turn if the Ornery Time and Space Die attacks. If it is rerolled because of being Ornery, no extra turns will be given. 

 Inconsistencies: •^J (Time & Space Jolt): Will not give more than 1 extra turn if rerolled to an odd number.

**Comment by irilyth** [comment]
This is my January BFOTM.

**Comment by blackshadowshade** [comment]
So, I am uncertain what should happen when Time and Space dice split. How do I know whether the original die rerolled an odd value when there are multiple dice spawned?

**Comment by irilyth** [comment]
Radioactive says "All dice that decay lose the following skills: Radioactive (%), Turbo Swing(!), Mood Swing(?), [and, not yet implemented: Jolt(J), and Time and Space(^)]." so I think that if you attack with a %^ die which splits, it loses T&S before the new split dice get rerolled, and thus T&S doesn't activate.

**Comment by blackshadowshade** [comment]
Note to self: I'm probably going to need to keep track of dice and die products that were initially Time and Space dice before the attack was committed. Die values are cleared during recipe changing and die spltting, so in these cases, we don't actually have a value until we reroll the new dice, right at the end of the attack phase, which is very late in the attack logic.

**Comment by blackshadowshade** [comment]
What about berserk?

**Comment by irilyth** [comment]
Berserk halves, not splits, so there's still only one die when you're done. So unless there's some reason to think otherwise, I'd assume that if a B^ die attacks and shrinks, T&S works on the new half-size die just like on any other size-changing die (e.g. Weak, Mighty, Mood, Turbo).

Radioactive seems like a unique case because you (might) have two dice after the attack, and you don't know which value to look at. Anything that "changes the size of a die" (by replacing it with a new die), I don't think you have that problem, right?

**Comment by blackshadowshade** [comment]
I think that I'm going to disagree regarding radioactive. I think that Time and Space *should* take effect on split, although the resulting dice will not continue to have Time and Space. In this case, if either die product ends up rolling even, then the player gets to play again.

i.e., T&S splitting, either by being radioactive or capturing radioactive, gives a better chance of having another turn.

Personally, I think that this is actually more fun, since it means that there is an active trade-off between getting an almost guaranteed extra turn now vs getting possibly more extra turns in the future.

**Comment by irilyth** [comment]
It just doesn't seem clean to me, because it means you have to keep track of whether a die *used to* have T&S earlier in the turn, or you have to keep it on the two split dice until after the reroll and then remove it, or some other weird thing. It seems much cleaner to me to say that when the die splits, the two dice don't have T&S when they come into play, and thus it doesn't matter what they roll.

Are there any current buttons that have both Radioactive and Time & Space?

**Comment by blackshadowshade** [comment]
New Mexico has both skills. Of course, the problem will occur any time any button with Time and Space is faced with any button with Radioactive.

**Comment by blackshadowshade** [comment]
Okay, I'm happy to go with irilyth's interpretation, because the skill triggers on reroll, and by this time, Time and Space has been lost for split dice.
