### ISSUE TITLE
Unique die skill needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#265]
Unique: u
I think unique is similar to weak, in that it was a skill created to handle rules that were simply spelled out on the button.

---

(Implemented, but not found listed in the original site captures, nor in the randomdice buttonmen roster)

Unique dice were created as a way to handle Guillermo's special rules[my best guess, not verified].  The unique skill applies when a button recipe has two or more swing dice [can it also be applied to option dice?].  Swing selection will fail if any two of the unique dice were assigned the same size.

Questions: Can Unique be assigned to dice other than swing [or option]?  example 'u(10) u(X)' meaning the X can be given any value other than 10
Can Unique be assigned to Mood Swing?  to Turbo?

**Comment by blackshadowshade** [comment]
Adding the button Gordo to this issue.

**Comment by irilyth** [comment]
Hmm, I feel like Gordo's ability is a button special, not a skill; in particular, if Gordo got a Aux die, I think that the "None of Gordo's dice can be the same size." rule would apply to them too. (Although that's vaguely problematic if Gordo gets an Aux X swing die; maybe Gordo *can't* take an Aux X swing die, due to their special? That seems correct to me, if unpleasantly complex.)

It matters less for Guillermo, since Guillermo's special ability only applies to the X and Y swing dice, so getting Aux dice doesn't change anything. I'd still be inclined to argue that this should be a button special ability rather than a die skill, and drop it as a die skill entirely.

**Comment by blackshadowshade** [comment]
So, my approach here is to implement this at the button level, and not at the die level, both for Gordo and Guillermo.
