### ISSUE TITLE
WildCard Die skill needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#266]
Wildcard: C
Wildcard Dice were created for the Wildcard Button Man in the Las Vegas Expansion by Ryan McGuire (aka Ryan). They are represented by a "C". Wildcard Dice are not rolled. Instead the computer simulates pulling a card from a deck of playing cards with two jokers. The value of the die is the the value of the face card, where Jack, Queen, King, Ace and Jokers have a value of 11, 12, 13, 14 and 20 respectively. In this web site, the cards are not removed from the deck, like in the rules, instead the same card can be drawn for multiple Wildcard dice. This aspect differs from original rules of Wildcard. Wildcard dice are worth 16 sides, as if it were a 16 sided die

 Clarifications: •
CF (WildCard Fire): Can not be Fired down below 2. Can be Fired down to 19-17 from a Joker (illegal values). 

 Inconsistencies: 
•CB (WildCard Berserk): Berserk Wildcard dice do not halve. The die is still worth 16 sides after a Berserk Attack 
•CH (WildCard Mighty): Mighty does not work with Wildcard. 
•Ch (WildCard Weak): Weak does not work with Wildcard. 
•Cs (WildCard Shadow): Shadow Wildcard dice can only capture dice showing a value between the current value of the die and 16. If it rolls a 20 (Joker) then it can NOT shadow attack at all. 

 Bugs: 
•Cf (WildCard Focus): Wildcard Focus dice are illegal, and do not work properly. 

NOTE: from boardgamesgeek list
Wildcard uses a deck of cards.  A number card is the number shown, jack through king are 11 through 13, a joker is a 20.  An ace is a 1, but is treated as a 14 when making power attacks. All cards are discarded face down (so that they cannot be reviewed) and are scored as d16s.

**Comment by TheOrgg** [comment]
Copy and pasted the Contents box from https://buttonmen.fandom.com/wiki/Button_Men_Rules and thought to go through the skills and variable dice one by one since Morph is a thing, and it looks like people expect a Morph (X) to become a Morph (C) when it attacks a Wildcard die.

Skills that I have questions about the interaction:
Fire Dice:  You could fire it to a number it doesn't actually have, or lower it into those ranges.  I know it's a bug, but I like Queer/Fire, I don't think it's worth pulling it from the site, just fix it when you get to it.

Focus Dice: Ace counts as 1 unless doing a PA, so the only real problem here is getting a Joker and dialing it from 20 to numbers the die doesn't actually have.  Also, if you set it downwards, does that remove that number from the deck?

Maximum Dice: Same as an M(20), I'd presume?

Morph Dice:  This is the reason I'm taking the time to type this out.

Ornery Dice:  I assume a shuffle is included if the deck runs out of cards to deal?

Shadow Dice:  Hmmm...  Does it go to 20?  Does it go to 12?  Can an A get anything up to that, or is it counted as a 14?
Queer Dice:  Solve shadow, then it should work.

Stinger Dice:  This one might have corner cases, but I can't think of any other than using it as one of the numbers the die can't physically give.  Since A can be used as 1, even going to 1 should be okay, yes?

Twin Dice:  Would a (C, C) work?  What about a mixed Twin with one (C) and one not?


Unimplemented interactions:
Cross Dice:   Would Ace count as a 1 or a 14 for Cross attacks?  (Cross Attacks are "multiplicative skill attacks")



Probably okay, but might need clarification.
Trip Dice:  This should work, and could have a 'card counting' element to it for more advanced players since there's no replacement.



Recipe setting effects
Option/Select/Batch - should work.

Armor Dice:  Should work.
Assassin Dice:  Should work.  They'd double the value on the die when it attacks.
Aggressive Dice:  +1 on your turn.  Other than putting it to numbers that aren't usually available, this should work.
Auxiliary Dice:  Should work.
Berserk Dice:  Works, but doesn't shrink.
Boom Dice:  Reminds me of Gambit from the X-Men.  Should work fine, though.
Chance Dice:  "Hit me."  Should work.
Chase's Giant Sized Die:  Wildcard SMASH!  Since this skill is an unbounded boost, it should work just fine.
Deception Dice:  Almost built-in, it seems.
Defensive Dice:  +1 on opponents' turns.  Should work.
Dodge Dice:  (C) would be worth 32 points if they had Dodge.  Rough!  Other than that, they should work.
Doppelganger Dice:  Should work, both against and with (C) dice.
Dual Dice/Evil Dice:   Should work.
Fudged Dice:  (the term I use for things like Shamrock Dice, Formula DE Dice, etc with a nontraditional or custom numbering.  Essentially Wildcard is a giant version of one of these.)
Full Auto Dice:  This and Wildcard makes me want to see an unofficial X-Men set with Gambit having a few of these.
Gamer Dice (https://github.com/buttonmen-dev/buttonmen/issues/360):  Gotta figure out how the hell these are supposed to work first...
Hoskin's Die:  Rush and Speed's rather awful cousin.  Should work.
Insult Dice:  Should work.  Extremely well.
Jolt Dice:  Should work.
Konstant Dice:  Should work.  "Is this your card?"
Kubla's Treasure Die:  Likely the second-to-last set of skills, so *shrug.*
Lucky Dice:  Should work.
Null Dice:  Should work.
Plasma Dice:  Should work.  a 'moody plasma' with four skills could be very fun IRL using the suits...
Poison Dice:  Should work.
Rage Dice:  Should work.
Rebound Dice:  Should work.
Reserve Dice:  Should work.
Rush Dice:  Should work.
Screw Dice:  Heh.  Should work, though.
Speed Dice:  Brutal.  Should work, though.
Sleep Dice:  Should work.
Slow Dice:  Should work.
Stealth Dice:  Ugly, but it should work.
Teleport Dice:  I guess it'd work.
Thief Dice:  I guess it'd work.
Time and Space Dice: This should work.
Value Dice:  Should work.
Warrior Dice: Should work, but would it be a 16 or 20?  (wouldn't be too good either way)

Doesn't have any effect:


Mighty Dice:  
Radioactive Dice:
Weak Dice:
