### ISSUE TITLE
Add pronouns to player profiles, and improve gender options

### ISSUE THREAD

**Issue by jl8e** [buttonmen-dev/buttonmen#2709]
I see this was discussed back in #1068, but I think the gender field needs a bit of revisiting and supplementing.

Nonbinary people are common enough that I think they should have their own entry in the dropdown.

I also think that "It's complicated" opening up a text box isn't obvious, and something like "Enter your own" would be better.

Whether or not we adjust the gender field, I think it's worthwhile to have a separate pronoun field.

Like gender, it'd be a customizable text field.

Off the top of my head, I'd include the following options:

Unspecified
she/her
he/him
they/them
it/its (An actual robot)
none (use my name)
Custom

I'd probably also add a couple of the more common other pronouns (xie/hir), but that requires a bit more research.

**Comment by cgolubi1** [comment]
Oh, thank you for filing this.  I've had it in the back of my mind for awhile to either file and issue or just do it; i agree that when we started out building the site, there wasn't consensus on the best approach, and since then everyone has standardized on having a pronouns field, so we should catch up.

**Comment by cgolubi1** [comment]
Should we use a drop-down at all, or just make it a free text field for everyone?  I think free text field is more inclusive, and not significantly more burdensome to people who like one of the options we thought of.

**Comment by jl8e** [comment]
I think we should use a dropdown; it creates less friction for the people who've never had to think about their pronouns. We'll likely see more usage than if we just have a text box.

Also you can just lift the code you used for the gender field, which makes it easy.

**Comment by irilyth** [comment]
I think a freeform text field is much better. I think the goal is to make it possible for people who want to use it to use it in whatever way they want; not to make it easy for people who don't care at all to put something in there. If most people don't bother to put in pronouns who cares? If someone who wants to feels like they can't because the menu is too limited, I think that's what we care about.

**Comment by jl8e** [comment]
The dropdown will include a text field option

And I think we want to encourage usage, so that people who think to check a profile for it are likely to get something when they do

**Comment by TheOrgg** [comment]
I love this.  I know a friend who'd like ge/ger as an option.
