### ISSUE TITLE
Pages do not appear to be updated after deployment

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2818]
At the moment, I'm looking at the live site and I cannot see the changes to broken links that were implemented in #2783.

In #2797, we implemented mod_pagespeed to handle caching of JS pages. My expectation was that the new pages should show the deployed changes, but I'm not seeing this yet.

**Comment by cgolubi1** [comment]
Shadowshade: can you provide the exact URLs that don't show the changes?

**Comment by cgolubi1** [comment]
One thing i noticed from a cursory comparison of #2783 with the website, is that that commit changes the text on https://www.buttonweavers.com/ui/help/index.html which *is* a valid page, but is *not* the same page, and doesn't have the same contents, as https://www.buttonweavers.com/ui/help.html --- the latter is what the Help footer on the overview points to.

This isn't familiar to me at all; i haven't been very involved in the help page PRs, so i have no idea why there are two pages with different contents.  I'll start on the assumption that no one knows anything about this and get to reverse-engineering, but if someone does know, weigh in!

**Comment by blackshadowshade** [comment]
Under Safari, looking for example at http://www.buttonweavers.com/ui/game.html?game=81108, I see the footer with the old links still when I mouseover them: www.cheapass.com and www.beatpeopleup.com.

At http://www.buttonweavers.com/ui/help.html, I still see buttonweavers.wikia.com when I mouseover the Buttonweavers wiki link.

And at http://www.buttonweavers.com/ui/, I still see the old www.cheapass.com/node/39/ link on mouseover of the Buttonmen link.


Maybe it's a https vs http thing?

**Comment by cgolubi1** [comment]
As far as i can tell, those two help pages just both exist, and no commits have ever touched both:

```
$ git log src/ui/help.html 
commit 75d9f65c0c1dc18e6a7bd8a1ae3164f94df50978
Author: Chaos <walrus-github@glassonion.org>
Date:   Thu Dec 30 17:02:37 2021 -0500

    Install mod_pagespeed in lieu of custom timestamp-based versioning

commit af82fc4ca36005224fcbfe7f7f27b5bc8448c126
Author: James Ong <blackshadowshade@gmail.com>
Date:   Fri Jan 15 10:56:58 2016 +0100

    - Added help link to footer
    - Added help page
    - Removed help text from footer and shifted it to the help page
    - Changed direct JS links to indirect links to the VERSION_COOKIE version
    - Made the help page display even when logged out
    - Standardised help HTML page
    - Added QUnit tests for new help page
    - Added stub help files
```

```
$ git log src/ui/help/index.html 
commit 1abbfe9f1142e90f9e9dcc3f4b4d9af7ed24c7af
Author: Dan Langford <721364+danlangford@users.noreply.github.com>
Date:   Fri Nov 19 22:12:45 2021 -0700

    fix or remove broken links resolves #2781 and more found along the way

commit 8fc494994c5ea1b26224b77c200537336c5c2430
Author: James Ong <blackshadowshade@gmail.com>
Date:   Tue Jan 5 09:11:13 2016 +0100

    Changed copyright year to 2016

commit 11c05e97343345de3ca96e42f427a02494d5a845
Author: James Ong <blackshadowshade@gmail.com>
Date:   Sat Jan 24 01:33:10 2015 +1100

    Changed copyright year from 2014 to 2015

commit 1bbbc080e0945ac4ca2b57fb395ccd9f991f2b8a
Author: Josh Smift <irilyth@infersys.com>
Date:   Thu Jul 31 22:39:34 2014 -0400

    Fix link to CSS style sheet.

commit ec9198f797468be58055ea3487f70045330ed13d
Author: Josh Smift <irilyth@infersys.com>
Date:   Thu Jul 31 22:34:29 2014 -0400

    Respect the soft limit of 80-character lines, and tune the copyright/terms paragraph.

commit 8421e94dc770c7dc6cb77b2ad2c1aa78bf4724af
Author: Josh Smift <irilyth@infersys.com>
Date:   Thu Jul 31 22:22:28 2014 -0400

    First draft of top-level help page.
```

**Comment by cgolubi1** [comment]
Summarizing everything i just said about the help thing:
* We simply have two distinct help pages in the repo, `src/ui/help.html` and `src/ui/help/index.html`
* Dan made his changes to the latter (index.html); those changes are visible on the live site
* The site "help" footer points to the former, which wasn't changed by the PR, so it still has the old contents

I don't think the help thing has anything to do with pagespeed --- i think those three bullets explain it fully.

I'll look into the footer thing now.

**Comment by cgolubi1** [comment]
Here's the footer diff #2783 submitted:

```diff
-     [ "A", { "href": "http://www.cheapass.com" }, [ "www.cheapass.com" ] ],
+     [ "A", { "href": "https://cheapass.com" }, [ "www.cheapass.com" ] ],
      " and ",
-     [ "A", { "href": "http://www.beatpeopleup.com" }, [ "www.beatpeopleup.com" ] ],
+     [ "A", { "href": "https://beatpeopleup.cheapass.com" }, [ "www.beatpeopleup.com" ] ],
```

When i browse to http://www.buttonweavers.com/ui/game.html?game=81108 and mouse over the links:
* The first link has the words "www.cheapass.com" in the text, and the url points to https://cheapass.com
* The second link has the words "www.beatpeopleup.com" in the text, and the url points to https://beatpeopleup.cheapass.com

That's what #2783 does.  In that PR, the url were updated, but the text wasn't, so now the urls don't match the words on the live site, just like the PR says.

Shadowshade, if what you're seeing in safari doesn't match my description, could you snag a screencap?  Depending on browser settings, if you mouseover the link, the url will pop up somehow, so you should be able to get a screencap showing both text and URL.

**Comment by cgolubi1** [comment]
Oh, and when i logout at https://www.buttonweavers.com/ui/, i see the text "Button Men" pointing to https://cheapass.com/free-games/button-men/ --- it sounds like Shadowshade is actually seeing something different than i am there.

**Comment by cgolubi1** [comment]
I'm heading offline, so i can respond to this more tomorrow, but what i think is:
* We should cut a new issue for the duplicate help pages, unless there's some explanation i'm missing for how this is supposed to work
* #2817 should fix the only footer issue *i* see, once you get the unit test passing.  I'll merge that when i see a passing build
* It sounds like safari is showing Shadowshade stale data; i have no explanation for why that would be, i'm not seeing it, and a cursory google didn't turn up any reports of dealbreaker incompatibility between safari and mod_pagespeed or anything.  I think there's enough confusion caused by the first two bullets that i'd prefer to defer this until we're sure it's an issue, but if you point me at anything concrete, i'll certainly look into it.

**Comment by cgolubi1** [comment]
Oh, last thing, i double-checked http://www.buttonweavers.com/ui/ (non-SSL site), and i see the contents i expect on the front page there too.  So if there's an SSL-vs-not thing (which was one of Shadowshade's suggestions), it's not impacting me anyway.

**Comment by blackshadowshade** [comment]
I've checked with the laptop (MacBook Air M1) again on Safari, and this also doesn't show an updated link on the login screen.

Screenshot below, with mouseover text in the bottom left:

<img width="1440" alt="Screen Shot 2022-01-16 at 4 33 45 pm" src="https://user-images.githubusercontent.com/2898401/149648618-22f38b1e-45a3-428e-9d28-b6ba88b806f9.png">

**Comment by blackshadowshade** [comment]
I can now confirm that the footer links have updated on the laptop, but not the Button Men link.

**Comment by cgolubi1** [comment]
Shadowshade, can you prioritize weighing in on the help link thing?  I think it's the primary reason people are going to report "HEY THE UPDATE DIDN'T WORK", and i just haven't been paying attention to any of the history of these pages, and don't know whether there's a reason we're in this state, or if it's just a mistake.  I think we should get an issue cut for this ASAP, so we can reduce confusion.

Everyone else, if you're seeing stale content on the live site, and you know or think your problem wasn't caused by one of the two bugs in the release (the non-update of the text on the footer links, and the semi-duplicated help page), can you comment with:
* what full URL you loaded
* the text you see on the stale link
* the URL you see pointed to by the stale link
* what browser you're using
* what time you loaded the page (including timezone, so i can look it up in the logs)
So far i have the one report, from shadowshade on Safari.

**Comment by dwvanstone** [comment]
At 10:18AM (east coast time) on Sunday, January 16, I logged out of Buttonmen and loaded the login page:

http://buttonweavers.com/ui/

"This is the alpha version of the Buttonweavers implementation of Button Men."

The link on "Button Men" goes to  http://www.cheapass.com/node/39 

I'm using Firefox 95.0.2 on a MacBook Pro.


Three minutes later (10:21AM) I use Chrome on my MacBook Pro and see the correct link.

**Comment by cgolubi1** [comment]
Thanks, dwvanstone.  I don't have a good theory here, but will run some experiments when i have a chance, and see if i can introduce a problem that i can replicate.

My operating assumption is that this isn't a crisis --- the links were broken before this deployment, so if they fail to become unbroken, that's not a regression.  And we don't have UI changes that we're very close to merging, so we have a few weeks to figure this out.  I'd rather figure out mod_pagespeed than revert it; the way we were doing this before was overly complicated and had known bugs that were leading to blank pages, and we know mod_pagespeed works at least some of the time for some set of changes --- dwvanstone verified the Config.js changes on the dev site were working.  So i'm guessing there's just a config setting we need to find and fix to make it match the set of page elements we actually use.

**Comment by blackshadowshade** [comment]
Oh sorry, forgot to talk about the two help pages.

When I `git blame` https://www.buttonweavers.com/ui/help/index.html, I get that most of the content was contributed by irilyth in #1149.

I copied most of the content from there into the current help page at https://www.buttonweavers.com/ui/help.html.

This means that we can get rid of the old one and make the help page changes to the new version instead.

I'll get onto that later today.

**Comment by blackshadowshade** [comment]
I agree that we should persevere with mod_pagespeed, the changes that we're looking at here are not mission critical and are actually a good test of our new deployment strategy.

**Comment by blackshadowshade** [comment]
Issue #2821 opened.

**Comment by blackshadowshade** [comment]
I can force Safari to update its page by using the Developer > Empty Caches option.

**Comment by blackshadowshade** [comment]
I'm looking at https://www.modpagespeed.com/doc/filter-cache-extend, and I note that there are actually three filters: 

extend_cache_images, extend_cache_scripts, and extend_cache_css

When we tested, we tested with an image, and that worked well. I'm wondering whether we tested only one-third of the functionality, and perhaps my inability to see new JS is due to the settings for a different filter being different to the image filter.

**Comment by cgolubi1** [comment]
#2797 has the details of the testing we did (i don't agree that "we tested with an image" is accurate, but i also don't think arguing about it is useful whether i'm right or not).  Let me start looking into this now and see if i can reproduce the problems others have seen in a sandbox.

**Comment by cgolubi1** [comment]
So, sort of interestingly, i can verify that when i change the contents of a URL defined in `Overview.js`, i don't see the update in any kind of near-term timeframe (this is the same as what dwvanstone reported), but when i change the contents of a URL defined in `Login.js` (i.e. one that shows up in the footer), i do see the update within 5 minutes (which should be what mod_pagespeed gets us).

I want to call out that in #2224 we defined all AJAX loads of JS resources to force caching, even though the AJAX default is to internally use a cache-buster when loading resources which are detected as type `script` (find-in-page "cache" in https://api.jquery.com/jquery.ajax/).  If we stopped defining `cache: true` in our AJAX calls, what would happen?  I'll experiment.

**Comment by blackshadowshade** [comment]
I think it's interesting that at the top of each HTML page, we have:

  <link id="favicon" rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <meta http-equiv="Cache-control" content="no-cache" />

which would possibly explain why the favicon isn't caching, but the AJAX is.

**Comment by cgolubi1** [comment]
I suspect this is not trivial, and is related to how we're loading javascript pages, so i'm going to ignore all speculation on this issue that doesn't sound "on the right track" to me.  Everyone should feel free to speculate, i just want to make clear that i'm not going to reply to it by default, because otherwise i'll feel bad.  :>)

Okay, so, back on my track.  I think it's important that a change to `Login.js` is picked up at mod_pagespeed speed, and a change to `Overview.js` isn't.  Because how does that `Overview.js` functionality actually get loaded?

1. I modified and deployed Overview.js, changing Overview.pageAddIntroText()
2. that is called by Overview.showLoggedOutPage()
3. that is called by Login.getBody(), in particular as part of Login.pageModule
4. Login.pagemodule is set by Login.showLoginHeader()
5. which is invoked by index.html with the Overview argument

In order for a change to Login.js to take effect, the new Login.js has to get loaded, and index.html has to invoke an updated version of `Login.showLoginHeader()`.

In order for a change to Overview.js to take effect, the new Overview.js has to get loaded, and index.html has to get an updated version of the `Overview` variable from that page load, and pass that new version to `Login.showLoginHeader()`.

My theory is that there's a relevant difference between those two operations.

I also think that turning off the AJAX forced-caching will fix the issue (possibly not on the first deployment, because if you have a cached version of Loader.js which uses caching, then... you get the idea).

But that's effectively reverting the change we made on purpose in #2224.  Is that okay?  Won't that slow things down again for people on airplanes?

**Comment by blackshadowshade** [comment]
I agree that our issues looks like we're not correctly cache-busting AJAX caching.

A Stack Overflow thread (https://stackoverflow.com/questions/21076663/google-mod-pagespeed-for-ajax-loaded-content) suggests that there's a mod_pagespeed setting that might allow us to handle this too:

https://www.modpagespeed.com/doc/system#ipro

Do we have this on currently?

**Comment by cgolubi1** [comment]
Shadowshade, that won't make any difference.  The BROWSER is caching javascript resources, because we are telling it to.  mod_pagespeed is on the SERVER.  it's not magic.  it can't reach out to the browser and force the browser to send it a request.

**Comment by blackshadowshade** [comment]
I thought that the point of mod_pagespeed was to supply served documents that told the browser that something was new. Is this not true for the AJAX requests?

**Comment by cgolubi1** [comment]
So, there are two ways the browser can decide to use a cached asset rather than getting a new asset from the server over the network:
A. The browser can decide its cached asset is good, and use it without making any network request.
B. The browser can send a normal GET request, and the server can send a response which says "i'm not sending you a new asset because your cached asset is good.  use it!"

I'm pretty sure `mod_pagespeed` does B, and a little bit of poking and looking at my developer tools output makes me think it's specifically using the `ETag` strategy.  Whether we have that strategy configured correctly is a different matter entirely --- at a glance, i think something you said earlier was possibly correct (that we're configuring mod_pagespeed caching correctly for image assets, but not for HTML or JS assets).

But all of that is related to places where we're *not* caching, and should be.  This issue was opened because of places where we *are* caching, and shouldn't be, and my assertion is that the problem is that if we force AJAX to cache JS assets, and also have pages load other pages the way we do in our site code, it makes a whole big mess which is the cause of this particular issue.  In other words, i don't think mod_pagespeed is doing a single thing wrong to cause the functional problems we're seeing --- we're seeing those functional problems because we ripped out our static fingerprinting without turning off AJAX caching.

**Comment by cgolubi1** [comment]
BTW, the `no-cache` directive doesn't mean "don't cache" --- it means always validate against the server (and the server can return 304).  So it should be compatible with strategy B that i outlined.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control for the same thing with more words.

**Comment by blackshadowshade** [comment]
Ah, so we want to turn off browser caching and let the server worry about that?

**Comment by cgolubi1** [comment]
Basically.  That is, we definitely want to turn off caching of type A, because that's just causing us trouble (and i think if we tell AJAX not to cache, we'll be good there).

But if we want caching of type B, we need some kind of browser participation --- the browser has to send the `If-None-Match:` header.  And it isn't.  So we're definitely missing a second thing, and that *might* be a pagespeed thing, or it might be an apache thing, or it might be something else.  I'm still working on that part.

**Comment by blackshadowshade** [comment]
In that case, I'm happy to try reverting the AJAX caching. I guess someone has a way of testing page load speeds on a mobile phone on a poor connection?
