### ISSUE TITLE
Add rules of Button Men on our site

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2843]
In #2837, @jl8e mentioned that he would like the rules of Button Men on the site.

I think this is reasonable, but we've previously flagged that we need to explicitly clear this with relevant authorities so that we don't inadvertently breach copyright.

**Comment by jl8e** [comment]
If it's a concern (and if the rights-holders want to shut the site down, they have plenty of other places to complain), then we can write them out in our own words. Game mechanics are not themselves copyrightable.

(So, if we actually got into a problem with the rights holders, the site itself is legit, but we'd have to ditch the trademarked name and all the official sets)

However, I don't see any reason to think we wouldn't get permission.

**Comment by jl8e** [comment]
OK, I hashed out a tutorial that (I think) explains the full rule set. It can probably use some examples, particularly in scoring.

_How to Play Button Men_

Button Men is a simple dice game at heart, with enough strategy to
keep it interesting, and plenty of room for extra complexity to keep
it fresh.

Each player has a character, which usually has art, an amusing
description, and, most importantly, a recipe. The recipe is a set of
dice, usually five of them. The simplest possible recipe would be
something like:

(4) (4) (6) (10) (20)

Five dice, each with a specified size. That's not all that
interesting, so the basic recipe looks more like:

(4) (6) (10) (20) (X)

The "(X)" is another die, called a Swing Die. At the start of the game,
you secretly choose the size of the die, setting it to any size within
the Swing Die's range. For an X swing, that's between 4 and 20. There
are a bunch of available swing die ranges, but you don't need to worry
about the rest of them for now.

You are absolutely allowed to set your swing die to numbers that
aren't a "real" die type. This can get awkward playing in real life,
but we're on a computer, so we don't have to care. (You might also be
surprised at how few die sizes don't exist. Dice People will make
17-sided dice, just because they can.)

Similar to Swing Dice, there are also Option Dice. They're written
as two numbers separated by a slash, such as 4/12. Instead of letting
you choose from a range, you can only pick between the available
sizes.

(There are a few other ways to let players vary their recipes, but you
don't need to worry about them right now.)

_Dice Skills_

Some dice have special abilities that change the way they work. On
this site, they're indicated by adding a letter to the die in the
recipe, such as "c(10)", which is a 10-sided Chance die.

We're not going to explain any dice skills in this tutorial, but you
should know that they exist, and that whenever we explain a rule,
there's an implied "unless a die skill says differently".

_Starting the Game_

Once both players have picked their variable dice, they roll all their
dice. The player who has the lowest number showing on a die goes first
this round. If both players are tied for lowest, the next-lowest
number goes first. (And so on, until you find a number that's
different.)

So, if I roll:

1 3 6 7 20

And you roll:

1 2 20 20 20

We both have a 1, so we have to compare next-lowest dice. You have a 2
and I have a 3, so you go first this round. The rest of your rolls are
higher, but it doesn't matter.

In the rare cases when the numbers match all the way, who goes first
is determined randomly. (If you have more dice than me, and all the
dice matched until I ran out, you would go first.)

_Playing the Round_

Once we know who goes first, that player takes their turn. On your
turn, you will make an attack with one or more of your dice, and
capture one of my dice. My die is removed from play and put into your
score pile, and all the dice you attacked with are rerolled.

Once that happens, it's my turn, and I do the same. The round keeps
going until either we both pass in turn, or one of us runs out of
dice. At that point, we compare our scores to see who won the
round. (Scoring will be explained later.)

On your turn, you must attack if you can. You only pass when you
cannot attack. If there's a die you don't want to capture, you'll just
have to make other attacks and hope that you can't attack it when the
time comes. (Why wouldn't you want to capture a die? Die skills.)

_Attacks_

There are two types of attacks: Power and Skill

__Power Attacks__

In a Power attack, you use one of your dice to capture one of my dice
that's showing a number equal to or lower than the number on the die
you're attacking with.

__Skill Attacks__

In a Skill attack, you use any number of your dice to capture a single
die of mine. The numbers showing on your dice must add up to exactly
the number showing on mine.

Yes, you can make a skill attack with a single die showing the same
number as one of my dice. You could also make a power attack. Most of
the time, it doesn't matter, and you won't have to specify which type
of attack you made.

_Scoring_

Once the round ends, we calculate our scores. Having dice left does
not mean you automatically win the round.

Scores are calculated entirely on the size of the dice. The number
showing doesn't matter at all.

Dice you captured from me are worth points equal to their size. Dice
you still have in play are worth half their size in points. (Half
points are allowed.)

On the site, both players' current score will be tracked
automatically. It will also tell you that you are plus or minus some
number of 'sides'. If I am currently plus six sides, then if you
capture a six-sided die from me, the changes to our scores will leave
us tied afterward.

(You would gain 6 for having captured it, while I would lose 3 for
no longer having it in play. "Sides" makes it easier to think about,
and is just as accurate until die skills get in the way.)

If the final scores are equal, then the round is a tie. There are no tie
breakers.

_The Next Round_

Games of Button Men are played until one player wins a specified
number of rounds. On the site, it defaults to three, so you may have
to play up to five games to see who wins. (Or even more if you manage
to tie.)

Once you've determined the winner of the round, the loser gets to
change the value of any variable dice they have. (This is not
required, but it's an important part of strategy.) If there was a tie,
neither player may change their dice.

Then, each player takes their dice, rolls them, and you go back to
determining who goes first for the next round.

**Comment by blackshadowshade** [comment]
One thing that's probably necessary is a brief overview of the recipe syntax that we use when it first occurs in this explanation.

**Comment by blackshadowshade** [comment]
Alternatively, we put a full description of the recipe syntax in the FAQ.

**Comment by blackshadowshade** [comment]
Did you want to add a URL link to Dice People?

**Comment by blackshadowshade** [comment]
I find it a tad disturbing to use "mine" and "my" in this rule set, but maybe that's just me.

**Comment by blackshadowshade** [comment]
Otherwise, I like this set of rules a lot, good work, @jl8e.

I'll build a page for this once we get feedback from other testers.

**Comment by jl8e** [comment]
> Did you want to add a URL link to Dice People?

I wasn't meaning to invoke a specific group, just "the set of people who are way too serious about dice".

> I find it a tad disturbing [as in, disorienting] to use "mine" and "my" in this rule set, but maybe that's just me.

I was writing it in the style of a personal explanation, but also other constructions are just clunkier. I could rewrite it to not use "me", but I'd want to stick with "you".

**Comment by jl8e** [comment]
Also, we should run this tutorial by at least one person who doesn't know how to play. I can see if my fiancee is willing to be a test subject, though she has played once, but probably since forgotten.

**Comment by blackshadowshade** [comment]
It would probably also be useful to put a link to the skills page where you mention that we're not going to tell you more about skills, so they can read up if they're interested.

**Comment by blackshadowshade** [comment]
I have a friend who just joined the site, he's a professional science writer, so he could certainly give a good critique of this, considering that he doesn't know how to play yet.

**Comment by jl8e** [comment]
Yes, he'd be a good victim.

**Comment by Richard-Fromage** [comment]
Victim here.
It's a well-written, very clear guide. 
By the  end of it, I wanted to go beyond game mechanics and into strategy. 
Perhaps what I really wanted answered is the quesion: "Wherein lies the fun?"

**Comment by jl8e** [comment]
> Victim here.
> It's a well-written, very clear guide.

Thank you. 

> By the end of it, I wanted to go beyond game mechanics and into strategy.

I've just put together a basic strategy section that could be tacked on to the end:

_Really Basic Strategy_

- A large die like a 20-sider can often take several dice at the end,
  just by rolling high several times in a row. Save it for then if you
  can.
- But it's often worth it to risk your big die to take your opponent's.
- Look out for your opponent's skill attacks. Capturing a low-value
  die that is needed to capture your high-value die is usually better
  than capturing a high-value die.
- Watch the 'sides' difference. If you can take an opponent's die that
  pushes the difference higher than the remaining number of sides of
  your dice, do it. You will have won the round.


> Perhaps what I really wanted answered is the quesion: "Wherein lies the fun?"

I'm not sure how to address this one

**Comment by Richard-Fromage** [comment]
The guide seems to be fleshing out nicely - I look forward to reading it again when you've put it all together. 

One last very tentative suggestion - what about a demonstration game? "Consider these two recipes: (2) (4) (6) (20)  and (1) (3) (8) (10) (18). Let's see what might happen when they meet in the arena." The narrative could proceed via screenshots and commentary or through commentary alone. Since I have yet to play a game myself, I have no idea if this is a useful, practical or necessary suggestion - sometimes the best thing is just to jump in! And that could also (possibly) be a motivating addition - a direct link to a practice round?

**Comment by TheOrgg** [comment]
The one thing I'd suggest for the last "strategy" part is a variation of "Make sure to look at what your opponent can do next turn as well as what you could do.  You know what all the dice values will be except for the dice you attack with, so plan your attacks carefully.  You may be able to take a less-valuable die from your opponent and protect one of your own from a skill attack!

Not the best writing for it, but something to that effect...  Most people who review the game don't see where the strategy lies at first (if they ever do).  Pointing out that the game isn't just randomness might be helpful.

**Comment by jl8e** [comment]
That's already touched on in the "watch your opponent's skill attacks" bit. This isn't attempting to be comprehensive.
