### ISSUE TITLE
Non-ASCII characters are being rendered strangely

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2974]
I first noticed on [this forum thread](https://www.buttonweavers.com/ui/forum.html#!threadId=1056) that the é character in the thread's title got garbled somehow. A follow-up post shows up correctly, though, so this seems to only be a problem for past stuff. Other non-ASCII characters in that thread are also being rendered incorrectly, and it sounds like this is showing up in other contexts as well, like in-game chat. Possibly related to the database upgrade? @kierajreed also mentioned on Discord that https://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of could be related.

**Comment by blackshadowshade** [comment]
That's interesting. Previous iterations of dealing with Unicode characters are found in #968 and #1699.

**Comment by blackshadowshade** [comment]
Actually, I'm wondering if this has something to do with the recent migration to a new MySQL database. Maybe the settings weren't set to latin1, so we are reading the database entries incorrectly now.

**Comment by cgolubi1** [comment]
I'm sure it's due to the DB migration.  Any chance there are occurrences of this in the staging forums?  That would be ideal for testing fixes.

**Comment by blackshadowshade** [comment]
I don't see anything obvious on the staging forums. I think this is one of those times when it probably makes sense to do a manual copy of the contents of an incorrectly displayed field from the live database to the staging database.

**Comment by cgolubi1** [comment]
I made some progress on this (including reproducing this problem superficially on a dev site, though not in a way that lets me repro a fix yet), but the progress is too hard to summarize, and didn't leave things in a conclusive state.  It does seem to be a latin1 vs utf8 thing of some sort, but there are a lot of different fiddly places where those settings get set, and changing database/table/column defaults is different from changing the stored data, and there are unhelpful differences in the base situation between RDS and local site databases, and between databases that have been backed-up/restored and databases that haven't been.

Just a content-free update to say i'm still working on this.  No advice needed.

**Comment by cgolubi1** [comment]
I've now done quite a bit of poking at this, and can speak to a little bit of what's going on:
* At the 700000-foot level, as discussed before, the issue is latin1 vs UTF-8.  But just knowing that doesn't help us hugely, so let's zoom in a bit.
* There are effectively two relevant pieces of MySQL configuration:
    * 1. `character-set-server` - how mysqld interprets strings dynamically
    * 2. the type of each database column which contains text
* Both of those are more complicated than that in various ways (sets of defaults, collations, etc), but for our purposes, at the end of the day, those two things are the important ones, and they have to match in order for anything good to happen. 
* So, fundamentally, what happened when we upgraded to mysql80 and restored staging and prod databases from backups, is that (1) `character-set-server` changed from `latin1` to `utf8mb4`, while (2) the type of each column remained `latin1`.  Now they don't match, and nothing good is happening.  In particular, two important bad things are happening:
    * When people load games or forum posts which were recorded before the DB upgrade, which contain accents or emoji, those posts look garbled.
    * When people try to put emoji (but not accents) into posts or game chat, they get an internal error. 
* How to fix?  Well, we have two choices: downgrade (1) or upgrade (2).
* Upgrading (2) seems appealing because Unicode is the future/present/past and what are we even doing.  I tested using an individual database column (`forum_post.body`), and verified that the upgrade would make it possible to submit emoji again.  But there are two problems:
    * Most granular specification wins, so we have to upgrade the type of every individual database column which contains text.  That's not that big a deal, it's just a big for loop, but we'd have to do it, and it'd probably be slow on the production database because it does touch every field.
    * More problematically: mysql's field conversion doesn't actually convert the old text contents, just its type.  So we'd have to find all of the pre-upgrade entries, create a mechanism to convert them explicitly from `latin1` to `utf8mb4`.  The upshot is that this would take some serious grunge, and be pretty error-prone; it's not a fast fix.
* Downgrading (1) is easy --- it's a two-liner change to our mysqld config to tell it to use `latin1` again, restart mysqld, and then everything we stored in the DB before the upgrade is readable again, and people can submit emoji again.  Glorious victory, *except*:
    * We have to deal with non-ascii text people have entered since the database upgrade, while the server has been in this inconsistent state.
    * Good news is, we don't have to deal with emoji or other high-numbered unicode characters.  People have been getting internal errors trying to submit those, so they're not in the database.  Sort of yay.
    * Bad news is, people have been able to make posts containing accents, and it turns out that when the latin1 server tries to load those posts, something goes wrong in the chain from server to PHP to user.  F'rex, on my test site, i made a post containing "é".  Unicode for that is `\xc3\xa9`.  After site downgrade, PHP retrieves the column as `\xe9`, which seems like it should be correct latin1, but something ain't right about it, presumably some kind of metadata.
    * Upshot is: when we try to `json_encode()` that field to return it to the user, it errors out, and we return a blank entry to the user.  (And we the site admins won't know this happened because of #2983.)  And obviously that's quite a bit worse than anything that's happening right now, so we can't do that.
    * Also worth noting: changing server parameters for RDS will be a bit different from changing them for mysqld --- but at a glance, it looks like RDS exposes this kind of parameter in a pretty user-friendly way.  So we'd have to test it, but i think it'd just work.

So i'm a little conflicted about what to do:
* The downgrade is relatively easy and would fix problems with historical site content immediately, and the only dealbreaker is that we have to handle the posts with unicode that have succeeded since the upgrade, but it's quite a dealbreaker because those posts break page load if we don't handle them.
* The upgrade would be annoying and time-consuming and require a lot of testing, and would nominally leave us in a better place, but it wouldn't fix any of the historical site content; we'd go through that grunge and be in the same place we are now for that stuff.

**Comment by cgolubi1** [comment]
I should note that a big piece of technology i'm missing is the ability to iterate over a table and find fields whose contents are in particular states.  Maybe the upshot is that i need that no matter what, so i should try to build it at this juncture.

**Comment by cgolubi1** [comment]
Caveat to the above:
* When the database encoding was consistently connected as `latin1`, database entries were being input in valid *unicode*, like `\xc3\xa9`
* Now that the database is in this inconsistent state, database entries are being input in *latin1*, like `\xe9`

That's mildly surprising, and presumably it related to the fact that PHP itself is trying to do things in Unicode.  It also means we don't have to lose a ton of sleep over downgrading the DB, because it's not like our *site* isn't using Unicode; if the strings that are being stored in the actual database are encoding as multibyte in some slightly archaic way, kind of enh.

In particular, here's my script:

```
import MySQLdb
conn = MySQLdb.connect(...)
crs = conn.cursor()
select_sql = 'SELECT id,body FROM forum_post where thread_id=4'
result = crs.execute(select_sql)
rows = crs.fetchall()

for row in rows:
  try:
    row[1].decode('utf-8')
  except UnicodeDecodeError:
    newstr = row[1].decode('latin1').encode('utf-8')
    update_sql = 'UPDATE forum_post SET body="%s" WHERE id=%s' % (newstr, row[0]
)
    result = crs.execute(update_sql)
    print(result)
 
conn.commit()
```

So... that's not too bad.  And pretty easy to generalize to trawl for erroneously latin1-encoded columns in any table.  Given that, i think i have a proposal for how to proceed, which i'll put in a new comment.

**Comment by cgolubi1** [comment]
Okay!  The path forward:
* Address #2983, so that if we mess anything up and players are getting blank pages, we get a log message about it
* Write a script that crawls all freeform text fields in the database looking for latin1 encoded fields, and optionally updates those fields to utf8
* On each site:
    * Run the script, so text is back to being utf-encoded (this will make it malformed in the short-term, but will reduce the risk of broken pages after the next step)
    * Reconfigure mysqld to switch back to latin1
    * Run the script again, to find any accented entries people created between the first two steps, and fix those
* Profit

Feedback welcome, but at the moment i feel good about that, and plan to start working on it later this weekend.

**Comment by cgolubi1** [comment]
Also here are the settings to put in buttonmen.cnf to accomplish the downgrade:

```
character-set-server=latin1
collation-server=latin1_swedish_ci
```

**Comment by blackshadowshade** [comment]
I think the plan looks pretty good!

Is there any way to test this out on a copy of the live database with specific posts that we can use as specific test cases?

**Comment by cgolubi1** [comment]
Yeah, i'll definitely load some database entries from prod onto one of the other sites as part of testing.  I think i understand how to do that now, and it'll be especially valuable when i test on the dev RDS database.

**Comment by cgolubi1** [comment]
Other than `game_action_log.message`, which players can't control so it shouldn't be able to contain non-ascii, the only freeform `TEXT` fields in the DB are `forum_post.body` and `game.chat`.

**Comment by cgolubi1** [comment]
Okay, i'll actually put this up for PR soon, but just to demonstrate progress, here's the script so far:

```python
#!/usr/bin/python

import MySQLdb
import sys

DRYRUN = len(sys.argv) > 1 and sys.argv[1] == '--dry-run'

if not DRYRUN:
  confirm = raw_input("Update database for real (y/n)? ")
  if not confirm == 'y': sys.exit(1)

conn = MySQLdb.connect(user='root', db='buttonmen')
crs = conn.cursor()

def run_update(sqlstr):
  if DRYRUN:
    print(sqlstr)
  else:
    print(sqlstr)
    result = crs.execute(sqlstr)
    print(result)

def assert_text_field_okay(table, field):
  print("-" * 72)
  print("Verifying no non-utf8 entries in %s.%s" % (table, field))
  select_sql = 'SELECT id,%s FROM %s WHERE %s IS NOT NULL' % (field, table, field)
  result = crs.execute(select_sql)
  rows = crs.fetchall()
  for row in rows:
    try:
      row[1].decode('utf-8')
    except UnicodeDecodeError:
      print("Unexpectedly found a bad entry in %s.%s" % (table, field))
      raise

def check_and_update_text_field(table, field):
  print("-" * 72)
  print("Looking for non-utf8 entries in %s.%s" % (table, field))
  select_sql = 'SELECT id,%s FROM %s WHERE %s IS NOT NULL' % (field, table, field)
  result = crs.execute(select_sql)
  rows = crs.fetchall()
  for row in rows:
    try:
      row[1].decode('utf-8')
    except UnicodeDecodeError:
      newstr = row[1].decode('latin1').encode('utf-8').replace('"', '\\"')
      update_sql = 'UPDATE %s SET %s="%s" WHERE id=%s' % (table, field, newstr, row[0])
      run_update(update_sql)

# Fields that shouldn't be able to have bad values, but we want to check
assert_text_field_okay('buttonset', 'name')
assert_text_field_okay('button', 'name')
assert_text_field_okay('button', 'recipe')
assert_text_field_okay('button', 'flavor_text')
assert_text_field_okay('tag', 'name')
assert_text_field_okay('forum_board', 'name')
assert_text_field_okay('forum_board', 'board_color')
assert_text_field_okay('forum_board', 'thread_color')
assert_text_field_okay('forum_board', 'description')
assert_text_field_okay('game_status', 'name')
assert_text_field_okay('game_action_log', 'message')
assert_text_field_okay('die', 'recipe')
assert_text_field_okay('die', 'flags')
assert_text_field_okay('die_status', 'name')
assert_text_field_okay('tournament', 'description')
assert_text_field_okay('player_status', 'name')
assert_text_field_okay('player', 'name_ingame')
assert_text_field_okay('player', 'name_irl')
assert_text_field_okay('player', 'email')
assert_text_field_okay('player', 'image_path')
assert_text_field_okay('player', 'homepage')
assert_text_field_okay('player', 'die_background')
assert_text_field_okay('player', 'player_color')
assert_text_field_okay('player', 'opponent_color')
assert_text_field_okay('player', 'neutral_color_a')
assert_text_field_okay('player', 'neutral_color_b')

check_and_update_text_field('forum_thread', 'title')
check_and_update_text_field('forum_post', 'body')
check_and_update_text_field('game', 'description')
check_and_update_text_field('game_chat_log', 'message')
check_and_update_text_field('player', 'gender')
check_and_update_text_field('player', 'pronouns')
check_and_update_text_field('player', 'comment')
check_and_update_text_field('player', 'vacation_message')
    
if not DRYRUN: 
  conn.commit()
```

I tested this against the prod database without action log entries (for size) loaded onto a local docker sandbox, and per my spot testing the method above seemed to work and it looked pretty good.

**Comment by cgolubi1** [comment]
Note to self: i need to check that escaping double-quotes DTRT --- before i did that, the update blew up, so it's definitely more right than not, but i need to actually find and look at the relevant entry and make sure it looks correct.

**Comment by cgolubi1** [comment]
So, one proposal:
* Step 1: Test the DB downgrade in isolation: put up a PR that contains the DB downgrade and the script, and load it on a dev site with the staging DB as usual (including running the script, though it's mostly a noop).  Players can kick the tires and verify that *new* use of accents and emoji looks correct.
* Step 2: Test the DB downgrade on prod data: stand up a private site containing the prod database with the new code and having run the script, as i've been doing.  Use a dev discord to share screencaps of individual items from the prod site (e.g. public forum posts) as requested by testers.  (This is easier for me to do than figure out a method i like for standing up a partially protected site.)
* Step 3: Test the RDS cutover method: Once we've agreed we like the fix's player-visible effects, test it on the RDS-backed dev database.
* Step 4: Push the PR: technically this does nothing for staging and prod except make the cutover script available, but it will cause all new dev site databases to be instantiated in `latin1`.
* Step 5: Deploy to and cutover staging, deploy to and cutover prod, using the process tested in step 3.

What do you think, Shadowshade?  Does that work for you?  If not, what's missing that you'd need to feel confident in the fix.

**Comment by blackshadowshade** [comment]
That sounds okay. I'm happy to be one of the testers if that makes things easier, in case you want to IP-lock access.

**Comment by cgolubi1** [comment]
> That sounds okay. I'm happy to be one of the testers if that makes things easier, in case you want to IP-lock access.

So my suggestion for 2 is that i deploy the prod site somewhere only i have access to, and i'll share screencaps with folks.  That's easier than IP-locking, which would require a certain amount of futzing around with the ECS service that i don't feel like doing for something throwaway.

Does that sound okay?

**Comment by blackshadowshade** [comment]
Sure, that's fine.

What I'm looking for is:
- the broken display of the old Latin-1 text before the update
- the correct display of the new UTF-8 text before the update
- the correct display of both text types after the update

**Comment by cgolubi1** [comment]
I posted the following call for dev-testing to discord:

Okay!  Here's a dev site with the proposed fix for https://github.com/buttonmen-dev/buttonmen/issues/2974, the non-ascii encoding issues:
* DEV SITE: https://2974-fix-encoding.cgolubi1.dev.buttonweavers.com/
* There's a copy of the staging database loaded, on top of which i ran the DB fixing script i wrote.
* Here are things testers should be able to check using that site:
    * You can load game pages and forum pages without internal errors or other weirdness.
    * You can post text using accents and emoji, it succeeds and looks okay.  (irilyth, this *should* address the problem you've been having entering smileys using your phone)
    * Text with accents which has been entered since the database upgrade still looks correct --- specifically this forum thread - https://2974-fix-encoding.cgolubi1.dev.buttonweavers.com/ui/forum.html#!threadId=10 - and this game - https://2974-fix-encoding.cgolubi1.dev.buttonweavers.com/ui/game.html?game=676
* Here are things you won't yet be able to test:
    * Does this work on a site with a remote database rather than a local database? (you can't see the difference as a player, but this dev site we're testing with now has a local DB; prod has a remote DB)
    * Does this fix the corrupted accents and emoji from pre-database-upgrade on the prod site? (because there weren't any on the staging site)
* Please help me out by doing the following:
    * Look at the dev site, test the things in that first list, and let me know that you did and if anything looks wrong.
    * Keep track of what you test, so you can check it again on a similar dev site with a remote DB (coming soon!)
    * I'll be doing the testing of the production database offline and sharing screencaps for verification.  If you're willing to help with that, share some URLs of pages on the production site that have garbled emoji or accents.  Please stick to forum posts or games with public chat, so that i can share screencaps in this channel.

I suggest we primarily use discord to talk about specifics of testing, so that we're not sharing contents of chat messages on this public github issue.  But recording my post here for the record.

The branch being tested is https://github.com/cgolubi1/buttonmen/tree/2974_fix_encoding --- i haven't put up a PR yet, but will once i think we've done enough testing that we could consider approving one.

**Comment by cgolubi1** [comment]
Testers who are paying attention here rather than discord: i have now rebuilt the dev site https://2974-fix-encoding.cgolubi1.dev.buttonweavers.com/ so it is using a REMOTE database, and applied the same set of fixes for the encoding issue.  Please take a look, and rerun the set of tests you ran before.  I also opened a PR for this fix, which hopefully can be reviewed once that testing is complete.
