### ISSUE TITLE
Unable to create a new account. 

### ISSUE THREAD

**Issue by blinkingline** [buttonmen-dev/buttonmen#2977]
When trying to create a new account after entering the required information, an error appears that says "Too many new user requests from IP 10.0.1.132"

**Comment by cgolubi1** [comment]
I know what the problem is.  Thanks for reporting this, and i'll work on it ASAP.

**Comment by cgolubi1** [comment]
Okay, so: this is very old code:

```
commit 047e046b889d93ce28a8a2547363cf45ea947f10
Author: Chaos Golubitsky <walrus-github@glassonion.org>
Date:   Mon Mar 10 20:20:53 2014 -0400

    * only allow five accounts to be created from a given IP address
```

It was designed to only allow 5 account creations to be in progress from any given IP address, to slow down a certain method of spamming account creation.

However, now that we've moved to containers, every connection shows up as being from the IP address of the load balancer, rather than from the player's initial IP address.  So we now have a shared pool of validations that can be in progress, and when it's exhausted, no more accounts can be created, which is obviously not what we want.

This is a case where we want to do something immediately to unblock player creation.  The easiest thing to do is to just modify the `player_validation` table to use a different (bonus points if it's invalid) IP address for these entries, so that we get immediately unstuck (until we get stuck again, but this is just the mitigation step).

That database update looks like:

On staging:
```
select * from player_verification where ipaddr="10.0.0.4";
select * from player_verification where ipaddr="10.0.0.255";
update player_verification set ipaddr="10.0.0.255" where ipaddr="10.0.0.4";
select * from player_verification where ipaddr="10.0.0.4";
select * from player_verification where ipaddr="10.0.0.255";
```

Assuming that shows the expected results, do the same thing on prod:
```
select * from player_verification where ipaddr="10.0.1.132";
select * from player_verification where ipaddr="10.0.0.255";
update player_verification set ipaddr="10.0.0.255" where ipaddr="10.0.1.132";
select * from player_verification where ipaddr="10.0.1.132";
select * from player_verification where ipaddr="10.0.0.255";
```

I'm planning to go ahead and do that, and then i'll post again about a longer-term fix.

**Comment by cgolubi1** [comment]
Done, on both staging and prod.

**Comment by cgolubi1** [comment]
This just popped up again, increasing the urgency of a real fix.  I'm going to apply the mitigation above in https://github.com/buttonmen-dev/buttonmen/issues/2977#issuecomment-2285084683 to both staging and prod again.

**Comment by cgolubi1** [comment]
I never actually summarized my thoughts about a real fix here: what i was thinking was that we should replace the existing 5-per-IP check with a check that blocks account creation if more than 5 accounts have been created in the past 5 minutes (or some other number of minutes).  all we're really trying to do here is put a little speedbump in the way of spamming the account creation API, and we have a timestamp in the DB, so that should be easy to do.
