### ISSUE TITLE
It would be nice to be able to create a dev recipe on the fly for testing

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#344]
When creating a game, it'd be nice if you could manually enter an unofficial button recipe. This would be useful both during alpha testing (so we could, e.g., test a button that had both chance and focus dice on it) and later on (so players could try out their fanatics or other proposed button sets).

**Comment by blackshadowshade** [comment]
I've been thinking about this, and it might be reasonably easy to implement a generic CustomBM, with the recipe to be entered at game creation/acceptance time, or perhaps parsed from the game creation flavour text.

Naturally, we would mark this as a button special so that it could only be used on the dev site.

**Comment by nkmcalli** [comment]
Plus one for players wanting this on the production site to experiment.

**Comment by irilyth** [comment]
On the production site, or the dev site? I think we'd been talking more about the latter.

(I guess there is no "the dev site" any more, so I'm not sure exactly what that would mean, but we could certainly set up a relatively durable dev site for button recipe testing.)

**Comment by nkmcalli** [comment]
On the live production site.  So that players (not devs) could set up matches with experimental buttons for crazyness.

**Comment by AdmiralJota** [comment]
How close are we to being able to support this at this point?

If the UI were able to handle it, how much more work does the back end need? 

What would the back end require the front end to provide it with?

What would the back end need to give back to the front end that the front end doesn't expect to receive from it right now?

**Comment by blackshadowshade** [comment]
I think all we need here is a way to input the recipe into the UI, and validation process to ensure that this recipe is valid. I presume that validation would occur at a minimum somewhere in the backend, and the UI would need to handle any errors intelligently.

It should be trivial to create a responder function to pass this recipe to the backend. Pretty much all the backend work is in place, as you note with your comment about RandomBM.

**Comment by AdmiralJota** [comment]
Here's an updated (untested) NewGame.js that might handle the input fields adequately: https://gist.github.com/AdmiralJota/12a0a19c22a87cb7cd6f9da322f0292a

**Comment by blackshadowshade** [comment]
Looks reasonable. I'll see what I can do with this in the next couple of days.

**Comment by blackshadowshade** [comment]
@AdmiralJota, I've been looking at this, and I've made a few fixes. However, there's one that I'd like your help with.

Take the case where I'm using a standard button, but my opponent will be using a custom button. Then, I want the first customRecipeTd to be hidden but still blocking its space (i.e., display: none is not correct), so that the second customRecipeTd ends up in the correct location.

Can you tell me what changes are necessary to make this work?

**Comment by blackshadowshade** [comment]
BTW, my new version of NewGame.js can be found on my branch 344_custom_recipe:

https://github.com/blackshadowshade/buttonmen/blob/344_custom_recipe/src/ui/js/Newgame.js

**Comment by blackshadowshade** [comment]
That's great! Okay, now to link this page up to the backend.
