### ISSUE TITLE
Mad Swing dice

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#509]
Mad Swing: (&)
an upside down question mark is shown as the die size
About choosing (&):  Since this die represents a swing value (in addition to a skill) and would therefore be listed inside of parenthesis, I asked about using (?) like the way it was represented in cheapass' playtest notes. Chaos thought it would too easily be confused with mood swing, and suggested I use some other crazy looking symbol like the ampersand.  Viola!  The reason we can't just use an upside down question mark is that would require unicode and we're sticking with ASCII.

---

Mad Swing Dice were created for the Unexploded Cow set by Cheapass Games. They behave similar to Mood Swing Dice. A Mad Swing Die can be any size between 2 and 20, and randomly changes size each time it is re-rolled, with an equal probability of any even size. (Use a d20 to choose the new size, rounding up odd numbers).
QUESTION:  Can the oringal size of Mad Swing be odd, or is it always an even value between 2 and 20?

**Comment by TheOrgg** [comment]
I'm not sure if this is a big deal, but I just noticed that the Mad Swing when using Y can be set to 1, not to 2 as the lowest.  That's why I put a Q on the swing die chart to stand for the Mad Swing numbers available. (Q also looks like a bomb, slightly)

Should we put in Q or would that be too challenging with the & modifier?
