### ISSUE TITLE
Turbo swing skill needed

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#91]

**Comment by jimmosk** [comment]
I'm eager for another skill to join the party, so I'd like this to be my BFotM for March.

**Comment by jimmosk** [comment]
I'm going to roll this over into April; it's still the enhancement I'm most interested in seeing next (now that Time and Space is accomplished).

**Comment by jimmosk** [comment]
How about seeing what advances can get made towards Turbo?  I'm picking this as my BFotM.

**Comment by blackshadowshade** [comment]
So, I'm starting to work on this. I'd like people to start discussing how Turbo Swing should interact with other skills. Consider, but don't feel bound by, how the interactions worked on the old site. It's also useful to me to hear if you have no preference on certain interactions.

Skills that I think might be worth discussing:
- Berserk
- Chance
- Konstant
- Mad/Mood
- Mighty/Weak
- Morphing
- Ornery
- Radioactive

**Comment by dwvanstone** [comment]
I remember turbo option dice on the old site (such as 1/30!) but I don't remember turbo swing dice (X!). I'm sure they were there but maybe I just went from one extreme to the other all of the time.

First pass!

Turbo + Mad/Mood: Turbo allows you to control the change every time you roll it, but the Mad/Mood quality comes in when it is rolled for some other purpose (such as when the opponent trips it or if it is ornery). That allows us to use both of the qualities.

Turbo + Berserk: The Berserk halves the die size, but as soon as you reroll the die you get to choose the size again. (The size limits are not halved.) 

Turbo + Radioactive: The Radioactive text already says that we lose the Turbo characteristic. I think that's fine.

Turbo + Ornery: When you roll, you can turbo; when you don't roll, it rerolls randomly.

Turbo + Mighty/Weak: When you roll, you can turbo to the original sizes; when you don't roll, mighty/weak comes into play.

Turbo + Chance: I think since you are controlling the Chance die being rerolled you can change its size at that moment too.

Turbo + Morphing: When you roll, you can turbo to the original sizes; when you don't roll, morphing comes into play.

Turbo + Konstant:  Ugh. What happens now for a konstant ornery weak die? Does it keep its value but change # of sides? Do we have the precedent that a die can have 4 sides but show a 7?

**Comment by blackshadowshade** [comment]
You may need to rethink Turbo + Morphing.

Description of morphing: "When a Morphing Die is used in any attack, it changes size, becoming the same size as the die that was captured. It is then re-rolled. Morphing Dice change size every time they capture another die. If a Morphing die is captured, its scoring value is based on its size at the time of capture, and likewise if it remains in a player's dice at the end of a round."

**Comment by cgolubi1** [comment]
> Turbo + Ornery: When you roll, you can turbo; when you don't roll, it rerolls randomly.

Just checking: you mean by "rerolls randomly" that it keeps the same size, right?  I don't think Turbo should mimic Mad/Mood under any circumstances.

**Comment by cgolubi1** [comment]
> Turbo + Mighty/Weak: When you roll, you can turbo to the original sizes; when you don't roll, mighty/weak comes into play.

What if, when you roll, Turbo happens first, then Mighty/Weak is applied to the resulting size?  That seems most consistent.  Then we're not defining a new rule for the *interaction* of Turbo and Mighty/Weak, we're just saying (1) Turbo only happens when you're rolling the die and thus are at keyboard to enter a new size (which IMO is the right principle), and (2) if Turbo and Mighty/Weak are both being applied, Turbo happens first.

**Comment by cgolubi1** [comment]
FWIW, i think that same principle should apply to other size-changing skill interactions --- both Turbo and the other effect come into play, and the only question is in which order.  For Berserk, the suggestion was that Berserk happen first.  So maybe (contrary to my previous comment, i'm thinking as i type) we should do the same for Mighty/Weak and for Morphing.  So then the cumulative effect in each of those cases is that Turbo applies.

**Comment by cgolubi1** [comment]
> Turbo + Konstant: Ugh. What happens now for a konstant ornery weak die? Does it keep its value but change # of sides? Do we have the precedent that a die can have 4 sides but show a 7? 

We absolutely do not have this precedent.  It throws an internal error which i have seen many many times in testing.  Here's an easy fix, and this matches the Mighty/Weak behavior encoded in responder test `test_interface_game_033()` --- Konstant dice don't roll.  Therefore, any size-changing attacks which take place on roll can't happen, because Konstant dice don't roll.  So for Konstant Turbo, the Turbo is a noop.

**Comment by dwvanstone** [comment]
> You may need to rethink Turbo + Morphing.

I had written:

> Turbo + Morphing: When you roll, you can turbo to the original sizes; when you don't roll, morphing comes into play.

""When a Morphing Die is used in any attack, it changes size, becoming the same size as the die that was captured. It is then re-rolled."

It seems to me that, for a brief instant, the morphing die becomes the size of the die that was captured. However it is then re-rolled which brings in the Turbo power: the owner can choose the new size. 

So I still think that, in the end, if the owner controls the attack, the die becomes whichever size the owner chooses.

The only time morphing comes into play is if the morphing die is used in an attack not controlled by the owner, such as in a Socrates attack.

I think this is consistent and works - is there a case I've missed? (I easily could have missed it -- this was meant as a start of a discussion!)

**Comment by dwvanstone** [comment]
I wrote:
>    Turbo + Ornery: When you roll, you can turbo; when you don't roll, it rerolls randomly.

Chaos wrote:
> Just checking: you mean by "rerolls randomly" that it keeps the same size, right? I don't think Turbo should mimic Mad/Mood under any circumstances.

I have to admit my language wasn't clear. I was in a rush this morning when I wrote all that. My apologies!

I'm trying to set the consistent mode that when the owner controls the roll (through a Chance die rerolling or when instigating an attack) that the owner gets to choose the size of the turbo die.

In this case, I meant that if for some other reason a turbo ornery die is rerolled (due to opponent's trip or orneriness) that the owner does not get to change its size. It stays the same size.

**Comment by dwvanstone** [comment]
I wrote:

>  Turbo + Konstant: Ugh. What happens now for a konstant ornery weak die? Does it keep its value but change # of sides? Do we have the precedent that a die can have 4 sides but show a 7?

Chaos wrote:
> We absolutely do not have this precedent. It throws an internal error which i have seen many many times in testing. Here's an easy fix, and this matches the Mighty/Weak behavior encoded in responder test test_interface_game_033() --- Konstant dice don't roll. Therefore, any size-changing attacks which take place on roll can't happen, because Konstant dice don't roll. So for Konstant Turbo, the Turbo is a noop.

I like this. I'm happy with Turbo Konstant being a noop.

**Comment by irilyth** [comment]
I've skimmed some of the follow-ups, but not all of them, and haven't read closely, so here are some of my own thoughts, and then I'll see what other folks have said. :^)

I think "After your starting roll, you may change the size of a Turbo Die every time you roll it." is the main thing.

* Berserk: "Once a Berserk Die performs a Berserk Attack, it is replaced with a non-berserk die". I think this depends on whether you think that a new die coming into play in the middle of a round is "After your starting roll", or if it *is* the starting roll for this die. I sort of thing the latter, and that Turbo wouldn't trigger in this case.

* Chance: "you may re-roll one of your Chance Dice". That sounds like it fits "every time you roll it", so I think Turbo would trigger in this case.

* Konstant: By and large, Konstant dice don't reroll "after your starting roll", so most of the time Turbo wouldn't have a chance to trigger.

* Mad/Mood: "whenever they are rolled their size is set randomly". I think either this comes first, and then Turbo lets you change the size a second time, or Turbo comes first and then this changes the size randomly. I don't have a preference which it should be, and think that button designers should be discouraged from combining these unless they have a good reason to. (Do any current buttons combine them?)

* Mighty/Weak: "When a Mighty Die rerolls for any reason, it first grows" and "When a Weak Die rerolls for any reason, it first shrinks". I think either this comes first, and then Turbo lets you change the size a second time, or Turbo comes first and then the die grows or shrinks. I think the latter is more fun, and that the old site worked this way.

* Morphing: "When a Morphing Die is used in any attack, it changes size, becoming the same size as the die that was captured. It is then re-rolled." That sounds to me like it triggers at attack time, and that you could then use Turbo to change the size a second time.

* Ornery: "Ornery dice reroll every time the player makes any attack". Is this "you roll it" or not? I think the spirit of "every time you roll it" for Turbo was meant to imply "in an attack", so I think Ornery Turbo Swing dice shouldn't be able to change size, but I don't feel strongly about it.

* Radioactive: "All dice that decay lose the following skills: Radioactive (%), Turbo Swing(!), Mood Swing(?), Time and Space(^), [and, not yet implemented: Jolt(J)]. For example, a s(X=15)! (Shadow Turbo X Swing with 15 sides) that shadow attacked a radioactive die would decay into a s(X=7) die and a s(X=8) die, losing the turbo skill." Seems clear, and sounds fine to me.

One you didn't mention:

* Trip: "Roll both the Trip Die and the Target, then compare the numbers they show." So I think this is you rolling the die in an attack, which triggers Turbo, and you can change the size of a t(X)! before you roll it as part of the Trip Attack.

Ok, going back and reading things that others have said:

DVS says "when you roll" a lot -- do you mean "when you roll as part of an attack"? I think generally clarifying "roll as part of an attack" and "roll at any other time" would be a useful distinction.

Chaos said "Turbo only happens when you're rolling the die and thus are at keyboard to enter a new size (which IMO is the right principle)" -- I like that a lot, and this modifies my thoughts about Trip, specifically because when one of your (X)! dice is *targeted* by a Trip Attack, I think "you" aren't rolling it, and thus can't change the size, even though it's "part of an attack" in some sense. (Maybe "part of an attack" should be "attacking".)

Chaos said "FWIW, i think that same principle should apply to other size-changing skill interactions --- both Turbo and the other effect come into play, and the only question is in which order." -- I agree, but I don't think we need to be consistent about this between skills. If we want Mighty/Weak to happen after Turbo, but Morphing to happen before Turbo, I think that's fine, as long as we can explain it somehow.

Whew. YAY TURBO SWING!! Big thanks to James for opening this can of worms. :^)

**Comment by AdmiralJota** [comment]
**Morphing**: When a non-Turbo m(X) captures, say, a 2 sided die, does it become a proper 2-sided die, or does it become an X swing showing 2? If the former, then I don't think Turbo should trigger, because Turbo is only relevant for swing (and possibly option) dice. If the latter, then that's weird, but I guess I would expect Turbo to trigger after Morphing in that case. But, still weird. Aside: does Morphing ever turn a die _into_ a swing?

**Berserk**: I don't know if there's a good justification, but it seems like it'd be more fun for Turbo to happen before Berserk, because then both skills are having an effect: you're picking what size it splits from -- so if you pick 4, you get a 2-sider.

**Konstant**: If it already doesn't count as a roll for other effects, then being consistent with that is good.

**Mighty/Weak**: I agree that Mighty/Weak after Turbo is more fun.

**Chance**: Sure, why not let it Turbo.

**Trip**: I agree with the idea that it triggers when you're making an attack _with_ a Turbo die, but not when you're targeting one.

**Radioactive**: Sounds self-explanatory.

**Mad/Mood**: If someone is silly enough to put them on the same die, we should just execute them in some consistent order.

**Ornery**: For the sake of both game balance and UI convenience, it seems probably better if Turbo doesn't apply here. But there's an argument for consistency with mad/mood as well, so I don't have a strong opinion either way.

It sounds like we might want to make a list of what skills apply in what order, and then we can just point to that when we need to explain ourselves. Something like "Mood, then Mad, then Turbo, then Mighty, then Weak, then Berserk" maybe?

**Comment by dwvanstone** [comment]
> Morphing: When a non-Turbo m(X) captures, say, a 2 sided die, does it become a proper 2-sided die, or does it become an X swing showing 2? If the former, then I don't think Turbo should trigger, because Turbo is only relevant for swing (and possibly option) dice. If the latter, then that's weird, but I guess I would expect Turbo to trigger after Morphing in that case. But, still weird. Aside: does Morphing ever turn a die into a swing?

I forget that a 2-sided die is different than a swing die with 2 sides. It seems that the intent of morphing is simply to become the number of sides but not pick up or lose any properties. (Assuming twin dice is not a "property".) So I'd say m(X) retains its swingness even though the new die size may be outside the range of the swing letter.

I'd say that morphing never turns a die into a swing.

So I'm going for the "latter" (albeit weird) case. I would think morphing happens first, then the turbo power kicks in.

[Just for what I hope is clarification: if I own a 6-sided die showing 6 and a m(X)! currently at 4 sides showing 2, and you are Socrates and have a 4-sided die showing 4...you can use a Socrates attack to capture my 6-sided die. Then my m(X)! becomes a six-sided swing die with 6 sides, but I don't think the Turbo should kick in because it was you that caused the die to join in on the attack.]

**Comment by dwvanstone** [comment]
> DVS says "when you roll" a lot -- do you mean "when you roll as part of an attack"? I think generally clarifying "roll as part of an attack" and "roll at any other time" would be a useful distinction.

Better language might be "roll as part of your attack" versus "roll at any other time". I think because of the Socrates attack it has to be the owner that initiates the attack.

**Comment by AdmiralJota** [comment]
> It seems that the intent of morphing is simply to become the number of sides but not pick up or lose any properties. (Assuming twin dice is not a "property".)

Then what happens if you use your m(X) to capture a (6,6) twin die? Does it become an X swing with (6,6) sides?

I think that to play the devil's advocate, I will propose the opposite notion: that, for the sake of morphing, the die type (swing, twin, wildcard, etc.) be considered part of the die size. So if your m!(X=4) captures my (Y=10), your die morphs into m!(Y=10) -- and then Turbo is triggered, letting you set it to any size from 1 to 20.

**Comment by irilyth** [comment]
I think Morphing currently takes on the type of the target die, which means it becomes Twin, Swing, Option, or regular, as appropriate. The type of the day isn't part of the size, but it something that Morphing copies. We can test this pretty easily.

With Turbo, I agree with Jota: The Turbo skill could stick with the die, and if you morph into a Twin or Regular die, Turbo is meaningless, just like if you start with a (8,8)! or (20)! die without Morphing.

**Comment by dwvanstone** [comment]
>  I will propose the opposite notion: that, for the sake of morphing, the die type (swing, twin, wildcard, etc.) be considered part of the die size.

This sounds like a fun idea, although it takes a while to twist my mind around it. I like that you're thinking ahead to Wildcard dice (or even twin Wildcard dice). I like it.

It may be confusing to our users, but I like that it's consistent. (It also doesn't change anything we have running right now.)

**Comment by irilyth** [comment]
To restate this more clearly: I'm pretty sure that die size and die type are separate properties of the die; but that Morphing copies both of those properties.

**Comment by dwvanstone** [comment]
Onwards!

> Berserk: I don't know if there's a good justification, but it seems like it'd be more fun for Turbo to happen before Berserk, because then both skills are having an effect: you're picking what size it splits from -- so if you pick 4, you get a 2-sider.

Until the next time you use it at which point you can turbo it back to a 4-sider (or a 20-sider).  Sure, I don't have a strong opinion which order those two go.

> Mighty/Weak: I agree that Mighty/Weak after Turbo is more fun.

Sounds fine.

> Trip: I agree with the idea that it triggers when you're making an attack with a Turbo die, but not when you're targeting one.

Sounds fine.

> Mad/Mood: If someone is silly enough to put them on the same die, we should just execute them in some consistent order.

If we do turbo first, then that will be countermanded by the mad/mood change and it will be an unsatisfying user experience. (Why bother having a UI screen to set the size if the size is ignored?) If we do turbo after mad/mood that would be more satisfying.

> Something like "Mood, then Mad, then Turbo, then Mighty, then Weak, then Berserk" maybe?

This sounds good!

**Comment by AdmiralJota** [comment]
And I suppose Morphing would go at the start of that list.

**Comment by blackshadowshade** [comment]
I'm pretty sure that if a m(X=4) captures a (Y=20) die, it turns into a plain m(20) die.

**Comment by irilyth** [comment]
Nope, at least not in http://dev.buttonweavers.com/ui/game.html?game=2279, which has

> irilyth performed Power attack using [m(10):9] against [(X=4):4]; Defender (X=4) was captured; Attacker m(10) changed size from 10 to 4 sides, recipe changed from m(10) to m(X=4), rerolled 9 => 4

followed by

> irilyth performed Power attack using [m(X=4):4] against [(1):1]; Defender (1) was captured; Attacker m(X=4) changed size from 4 to 1 sides, recipe changed from m(X=4) to m(1), rerolled 4 => 1

so the m(10) changed to an m(X=4) and then back to an m(1).

**Comment by blackshadowshade** [comment]
Well, there you go. Learn something new every day.  :)

**Comment by blackshadowshade** [comment]
I'm linking #1143 here so that I can find it more easily.

**Comment by blackshadowshade** [comment]
The implementation of Turbo in BMInterface is currently blocked on #1942, since I don't want to have to deconflict the new game actions for Turbo.

**Comment by blackshadowshade** [comment]
So, I have a question about buttons with multiple Turbo dice with the same swing type. What happens when these Turbo dice attack at the same time?

For example, Ping has a recipe of (4) (8) (X)! (X)!.

Are both of the die sides forced to be the same, or can they be different to each other? I'm leaning towards being able to change the two independently. What do you all think?

**Comment by dwvanstone** [comment]
> For example, Ping has a recipe of (4) (8) (X)! (X)!.

They should be independent, otherwise we fall into the problem of having an N-sided die showing a value above N. (For instance, say the two (X)! dice have 20 sides at the beginning and they have rolled 20 and 20. If you use one of them to attack and then change its size to 4 the other one should not be a 4-sided die showing 20.)

**Comment by blackshadowshade** [comment]
As a teaser:
![grab](https://cloud.githubusercontent.com/assets/2898401/13352285/637b4ca8-dce0-11e5-870b-700d8ea2c41e.png)

We'll probably need the swing range there somewhere too, probably just underneath the turbo resize line.

**Comment by irilyth** [comment]
I agree with DVS, just like how (X)? (X)? would start at the same size, but then change independently over the course of the round.

**Comment by blackshadowshade** [comment]
I'm removing the BotM label from this because I've put in way more than two hours (and it's getting close to ready).  :)

**Comment by AdmiralJota** [comment]
I'm adding it back because I want to see it finished, so that we can start testing the Steven Universe set!
